# Data Collection

### 1. Steps to collect airport data using API and convert into sql

In [17]:
import time

In [ ]:
#checking whether the airport codes available 
import requests


url1= "https://aerodatabox.p.rapidapi.com/airports/icao/VIDP"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": API_HOST
}
response = requests.get(url1, headers=headers)
print(response.json())
#for values in url.values():
#    response = requests.get(values, headers=headers)
#    print(response.json())

{'icao': 'VIDP', 'iata': 'DEL', 'shortName': 'Indira Gandhi', 'fullName': 'New Delhi Indira Gandhi', 'municipalityName': 'New Delhi', 'location': {'lat': 28.5665, 'lon': 77.1031}, 'elevation': {'meter': 236.83, 'km': 0.24, 'mile': 0.15, 'nm': 0.13, 'feet': 777.0}, 'country': {'code': 'IN', 'name': 'India'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kolkata', 'urls': {'webSite': 'http://www.newdelhiairport.in/', 'wikipedia': 'https://en.wikipedia.org/wiki/Indira_Gandhi_International_Airport', 'flightRadar': 'https://www.flightradar24.com/28.57,77.10/14', 'googleMaps': 'https://www.google.com/maps/@28.566499,77.103103,14z'}}

In [75]:
#Connection to the url with key
import requests
API_HOST = "aerodatabox.p.rapidapi.com"
API_KEY = "0141b76dd0msh10788ba6accf36fp139e9cjsn076f006dd959"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": API_HOST
}

In [27]:
#Defining a function with icao code
def fetch_airport_by_icao(icao_code):
    url=f"https://aerodatabox.p.rapidapi.com/airports/icao/{icao_code}"
    response=requests.get(url,headers=headers)
    time.sleep(1)
    return response.json()

In [43]:
my_airports=["EGLL", "KJFK", "OMDB", "VIDP", "VOBL", "EGCC", "EDDM", "CYVR", "RJOO", "WMKP", "VTCC", "EHAM", "LFPG", "WSSS", "YSSY"]

airport_all={}

for icao in my_airports:
    try:
        airport_data=fetch_airport_by_icao(icao)
        airport_all[icao]=airport_data
        print(airport_data)
    except Exception as e:
        print(f"Error loading airport {icao}: {e}")

{'icao': 'EGLL', 'iata': 'LHR', 'shortName': 'Heathrow', 'fullName': 'London Heathrow', 'municipalityName': 'London', 'location': {'lat': 51.4706, 'lon': -0.461941}, 'elevation': {'meter': 25.3, 'km': 0.03, 'mile': 0.02, 'nm': 0.01, 'feet': 83.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.heathrow.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/London_Heathrow_Airport', 'twitter': 'https://x.com/HeathrowAirport', 'flightRadar': 'https://www.flightradar24.com/51.47,-0.46/14', 'googleMaps': 'https://www.google.com/maps/@51.470600,-0.461941,14z'}}
{'icao': 'KJFK', 'iata': 'JFK', 'shortName': 'John F Kennedy', 'fullName': 'New York John F Kennedy', 'municipalityName': 'New York', 'location': {'lat': 40.6398, 'lon': -73.7789}, 'elevation': {'meter': 3.96, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 13.0}, 'country': {'code': 'US', 'name': 'United States'}, 'continent': {'code': 'NA', 'name': 'North America'}, 'timeZone': 'America/New_York', 'urls': {'webSite': 'http://www.panynj.gov/airports/jfk.html', 'wikipedia': 'https://en.wikipedia.org/wiki/John_F._Kennedy_International_Airport', 'twitter': 'https://x.com/JFKairport', 'liveAtc': 'https://www.liveatc.net/search/?icao=KJFK', 'flightRadar': 'https://www.flightradar24.com/40.64,-73.78/14', 'googleMaps': 'https://www.google.com/maps/@40.639801,-73.778900,14z'}}
{'icao': 'OMDB', 'iata': 'DXB', 'shortName': 'Dubai', 'fullName': 'Dubai', 'municipalityName': 'Dubai', 'location': {'lat': 25.252798, 'lon': 55.3644}, 'elevation': {'meter': 18.9, 'km': 0.02, 'mile': 0.01, 'nm': 0.01, 'feet': 62.0}, 'country': {'code': 'AE', 'name': 'United Arab Emirates'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Dubai', 'urls': {'webSite': 'http://www.dubaiairports.ae/', 'wikipedia': 'https://en.wikipedia.org/wiki/Dubai_International_Airport', 'twitter': 'https://x.com/DubaiAirports', 'flightRadar': 'https://www.flightradar24.com/25.25,55.36/14', 'googleMaps': 'https://www.google.com/maps/@25.252799,55.364398,14z'}}
{'icao': 'VIDP', 'iata': 'DEL', 'shortName': 'Indira Gandhi', 'fullName': 'New Delhi Indira Gandhi', 'municipalityName': 'New Delhi', 'location': {'lat': 28.5665, 'lon': 77.1031}, 'elevation': {'meter': 236.83, 'km': 0.24, 'mile': 0.15, 'nm': 0.13, 'feet': 777.0}, 'country': {'code': 'IN', 'name': 'India'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kolkata', 'urls': {'webSite': 'http://www.newdelhiairport.in/', 'wikipedia': 'https://en.wikipedia.org/wiki/Indira_Gandhi_International_Airport', 'flightRadar': 'https://www.flightradar24.com/28.57,77.10/14', 'googleMaps': 'https://www.google.com/maps/@28.566499,77.103103,14z'}}
{'icao': 'VOBL', 'iata': 'BLR', 'shortName': 'Bengaluru', 'fullName': 'Bangalore Bengaluru', 'municipalityName': 'Bangalore', 'location': {'lat': 13.197899, 'lon': 77.7063}, 'elevation': {'meter': 914.4, 'km': 0.91, 'mile': 0.57, 'nm': 0.49, 'feet': 3000.0}, 'country': {'code': 'IN', 'name': 'India'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kolkata', 'urls': {'webSite': 'https://www.bengaluruairport.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/Bengaluru_International_Airport', 'twitter': 'https://x.com/BLRAirport', 'flightRadar': 'https://www.flightradar24.com/13.20,77.71/14', 'googleMaps': 'https://www.google.com/maps/@13.197899,77.706298,14z'}}
{'icao': 'EGCC', 'iata': 'MAN', 'shortName': 'Manchester', 'fullName': 'Manchester', 'municipalityName': 'Manchester', 'location': {'lat': 53.3537, 'lon': -2.27495}, 'elevation': {'meter': 78.33, 'km': 0.08, 'mile': 0.05, 'nm': 0.04, 'feet': 257.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.manchesterairport.co.uk/', 'wikipedia': 'https://en.wikipedia.org/wiki/Manchester_Airport', 'twitter': 'https://x.com/manairport', 'flightRadar': 'https://www.flightradar24.com/53.35,-2.27/14', 'googleMaps': 'https://www.google.com/maps/@53.353698,-2.274950,14z'}}
{'icao': 'EDDM', 'iata': 'MUC', 'shortName': 'Munich', 'fullName': 'Munich', 'municipalityName': 'Munich', 'location': {'lat': 48.3538, 'lon': 11.7861}, 'elevation': {'meter': 453.24, 'km': 0.45, 'mile': 0.28, 'nm': 0.24, 'feet': 1487.0}, 'country': {'code': 'DE', 'name': 'Germany'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Berlin', 'urls': {'webSite': 'http://www.munich-airport.de/', 'wikipedia': 'https://en.wikipedia.org/wiki/Munich_International_Airport', 'twitter': 'https://x.com/MUC_Airport', 'flightRadar': 'https://www.flightradar24.com/48.35,11.79/14', 'googleMaps': 'https://www.google.com/maps/@48.353801,11.786100,14z'}}
{'icao': 'CYVR', 'iata': 'YVR', 'shortName': 'Vancouver', 'fullName': 'Vancouver', 'municipalityName': 'Vancouver', 'location': {'lat': 49.1939, 'lon': -123.184}, 'elevation': {'meter': 4.27, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 14.0}, 'country': {'code': 'CA', 'name': 'Canada'}, 'continent': {'code': 'NA', 'name': 'North America'}, 'timeZone': 'America/Vancouver', 'urls': {'webSite': 'http://www.yvr.ca/', 'wikipedia': 'https://en.wikipedia.org/wiki/Vancouver_International_Airport', 'twitter': 'https://x.com/yvrairport', 'liveAtc': 'https://www.liveatc.net/search/?icao=CYVR', 'flightRadar': 'https://www.flightradar24.com/49.19,-123.18/14', 'googleMaps': 'https://www.google.com/maps/@49.193901,-123.183998,14z'}}
{'icao': 'RJOO', 'iata': 'ITM', 'shortName': 'Osaka', 'fullName': 'Osaka', 'municipalityName': 'Osaka', 'location': {'lat': 34.7855, 'lon': 135.438}, 'elevation': {'meter': 15.24, 'km': 0.02, 'mile': 0.01, 'nm': 0.01, 'feet': 50.0}, 'country': {'code': 'JP', 'name': 'Japan'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Tokyo', 'urls': {'webSite': 'https://www.osaka-airport.co.jp/', 'wikipedia': 'https://en.wikipedia.org/wiki/Osaka_International_Airport', 'liveAtc': 'https://www.liveatc.net/search/?icao=RJOO', 'flightRadar': 'https://www.flightradar24.com/34.79,135.44/14', 'googleMaps': 'https://www.google.com/maps/@34.785499,135.438003,14z'}}
{'icao': 'WMKP', 'iata': 'PEN', 'shortName': 'Penang', 'fullName': 'Penang', 'municipalityName': 'Penang', 'location': {'lat': 5.29714, 'lon': 100.277}, 'elevation': {'meter': 3.35, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 11.0}, 'country': {'code': 'MY', 'name': 'Malaysia'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kuala_Lumpur', 'urls': {'webSite': 'https://airports.malaysiaairports.com.my/', 'wikipedia': 'https://en.wikipedia.org/wiki/Penang_International_Airport', 'twitter': 'https://x.com/MY_Airports', 'flightRadar': 'https://www.flightradar24.com/5.30,100.28/14', 'googleMaps': 'https://www.google.com/maps/@5.297140,100.277000,14z'}}
{'icao': 'VTCC', 'iata': 'CNX', 'shortName': 'Chiang Mai', 'fullName': 'Chiangmai Chiang Mai', 'municipalityName': 'Chiangmai', 'location': {'lat': 18.7668, 'lon': 98.9626}, 'elevation': {'meter': 315.77, 'km': 0.32, 'mile': 0.2, 'nm': 0.17, 'feet': 1036.0}, 'country': {'code': 'TH', 'name': 'Thailand'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Bangkok', 'urls': {'webSite': 'https://chiangmai.airportthai.co.th/', 'wikipedia': 'https://en.wikipedia.org/wiki/Chiang_Mai_International_Airport', 'twitter': 'https://x.com/AOTthailand', 'flightRadar': 'https://www.flightradar24.com/18.77,98.96/14', 'googleMaps': 'https://www.google.com/maps/@18.766799,98.962600,14z'}}
{'icao': 'EHAM', 'iata': 'AMS', 'shortName': 'Schiphol', 'fullName': 'Amsterdam Schiphol', 'municipalityName': 'Amsterdam', 'location': {'lat': 52.3086, 'lon': 4.763889}, 'elevation': {'meter': -3.35, 'km': -0.0, 'mile': -0.0, 'nm': -0.0, 'feet': -11.0}, 'country': {'code': 'NL', 'name': 'Netherlands'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Amsterdam', 'urls': {'webSite': 'http://www.schiphol.nl/', 'wikipedia': 'https://en.wikipedia.org/wiki/Amsterdam_Schiphol_Airport', 'twitter': 'https://x.com/Schiphol', 'liveAtc': 'https://www.liveatc.net/search/?icao=EHAM', 'flightRadar': 'https://www.flightradar24.com/52.31,4.76/14', 'googleMaps': 'https://www.google.com/maps/@52.308601,4.763889,14z'}}
{'icao': 'LFPG', 'iata': 'CDG', 'shortName': 'Charles de Gaulle', 'fullName': 'Paris Charles de Gaulle', 'municipalityName': 'Paris', 'location': {'lat': 49.0128, 'lon': 2.549999}, 'elevation': {'meter': 119.48, 'km': 0.12, 'mile': 0.07, 'nm': 0.06, 'feet': 392.0}, 'country': {'code': 'FR', 'name': 'France'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Paris', 'urls': {'webSite': 'http://www.parisaeroport.fr/', 'wikipedia': 'https://en.wikipedia.org/wiki/Charles_de_Gaulle_International_Airport', 'twitter': 'https://x.com/ParisAeroport', 'liveAtc': 'https://www.liveatc.net/search/?icao=LFPG', 'flightRadar': 'https://www.flightradar24.com/49.01,2.55/14', 'googleMaps': 'https://www.google.com/maps/@49.012798,2.549999,14z'}}
{'icao': 'WSSS', 'iata': 'SIN', 'shortName': 'Changi', 'fullName': 'Singapore Changi', 'municipalityName': 'Singapore', 'location': {'lat': 1.35019, 'lon': 103.994}, 'elevation': {'meter': 6.71, 'km': 0.01, 'mile': 0.0, 'nm': 0.0, 'feet': 22.0}, 'country': {'code': 'SG', 'name': 'Singapore'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Singapore', 'urls': {'webSite': 'http://www.changiairport.com/en/', 'wikipedia': 'https://en.wikipedia.org/wiki/Singapore_Changi_Airport', 'twitter': 'https://x.com/ChangiAirport', 'flightRadar': 'https://www.flightradar24.com/1.35,103.99/14', 'googleMaps': 'https://www.google.com/maps/@1.350190,103.994003,14z'}}
{'icao': 'YSSY', 'iata': 'SYD', 'shortName': 'Kingsford Smith', 'fullName': 'Sydney Kingsford Smith', 'municipalityName': 'Sydney', 'location': {'lat': -33.9461, 'lon': 151.177}, 'elevation': {'meter': 6.4, 'km': 0.01, 'mile': 0.0, 'nm': 0.0, 'feet': 21.0}, 'country': {'code': 'AU', 'name': 'Australia'}, 'continent': {'code': 'OC', 'name': 'Australia & Oceania'}, 'timeZone': 'Australia/Sydney', 'urls': {'webSite': 'http://www.sydneyairport.com.au/', 'wikipedia': 'https://en.wikipedia.org/wiki/Kingsford_Smith_International_Airport', 'twitter': 'https://x.com/SydneyAirport', 'liveAtc': 'https://www.liveatc.net/search/?icao=YSSY', 'flightRadar': 'https://www.flightradar24.com/-33.95,151.18/14', 'googleMaps': 'https://www.google.com/maps/@-33.946098,151.177001,14z'}}

In [49]:
import pandas as pd

def extract_airport_info(airport_data):
    extracted_info = {
        'icao_code': airport_data.get('icao'),
        'iata_code': airport_data.get('iata'),
        'name': airport_data.get('fullName'),
        'city': airport_data.get('municipalityName'),
        'country': airport_data.get('country', {}).get('name'),
        'continent': airport_data.get('continent', {}).get('name'),
        'latitude': airport_data.get('location', {}).get('lat'),
        'longitude': airport_data.get('location', {}).get('lon'),
        'timezone': airport_data.get('timeZone')
    }
    return extracted_info

In [50]:
extracted_airports_data = []
for icao, data in airport_all.items():
    extracted_airports_data.append(extract_airport_info(data))

# Create a pandas DataFrame from the extracted data
airport_df = pd.DataFrame(extracted_airports_data)
display(airport_df)

,icao_code,iata_code,name,city,country,continent,latitude,longitude,timezone
0,EGLL,LHR,London Heathrow,London,United Kingdom,Europe,51.470600,-0.461941,Europe/London
1,KJFK,JFK,New York John F Kennedy,New York,United States,North America,40.639800,-73.778900,America/New_York
2,OMDB,DXB,Dubai,Dubai,United Arab Emirates,Asia,25.252798,55.364400,Asia/Dubai
3,VIDP,DEL,New Delhi Indira Gandhi,New Delhi,India,Asia,28.566500,77.103100,Asia/Kolkata
4,VOBL,BLR,Bangalore Bengaluru,Bangalore,India,Asia,13.197899,77.706300,Asia/Kolkata
5,EGCC,MAN,Manchester,Manchester,United Kingdom,Europe,53.353700,-2.274950,Europe/London
6,EDDM,MUC,Munich,Munich,Germany,Europe,48.353800,11.786100,Europe/Berlin
7,CYVR,YVR,Vancouver,Vancouver,Canada,North America,49.193900,-123.184000,America/Vancouver
8,RJOO,ITM,Osaka,Osaka,Japan,Asia,34.785500,135.438000,Asia/Tokyo
9,WMKP,PEN,Penang,Penang,Malaysia,Asia,5.297140,100.277000,Asia/Kuala_Lumpur
10,VTCC,CNX,Chiangmai Chiang Mai,Chiangmai,Thailand,Asia,18.766800,98.962600,Asia/Bangkok
11,EHAM,AMS,Amsterdam Schiphol,Amsterdam,Netherlands,Europe,52.308600,4.763889,Europe/Amsterdam
12,LFPG,CDG,Paris Charles de Gaulle,Paris,France,Europe,49.012800,2.549999,Europe/Paris
13,WSSS,SIN,Singapore Changi,Singapore,Singapore,Asia,1.350190,103.994000,Asia/Singapore
14,YSSY,SYD,Sydney Kingsford Smith,Sydney,Australia,Australia & Oceania,-33.946100,151.177000,Australia/Sydney

In [64]:
airport_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   icao_code  15 non-null     str
 1   iata_code  15 non-null     str
 2   name       15 non-null     str
 3   city       15 non-null     str
 4   country    15 non-null     str
 5   continent  15 non-null     str
 6   latitude   15 non-null     float64
 7   longitude  15 non-null     float64
 8   timezone   15 non-null     str
dtypes: float64(2), str(7)
memory usage: 1.2 KB

In [33]:
#To make a connection to mysql
import mysql.connector 

connection = mysql.connector.connect(
    host = "Localhost",
    user = "root",
    password = "12345",
    )
cursor =  connection.cursor()
cursor

In [123]:
query="create database if not exists AeroDataBox"
cursor.execute(query)
connection.commit()

In [38]:
query = "use AeroDataBox"
cursor.execute(query)

In [59]:
query = """create table if not exists Airport(airport_id int primary key auto_increment, icao_code varchar(60) UNIQUE, iata_code varchar(60) UNIQUE, name varchar(60), city varchar(60), country varchar(60), continent varchar(60), latitude float, longitude float, timezone varchar(60))"""
cursor.execute(query)
connection.commit()

In [ ]:
columns = ",".join(airport_df.columns)
placeholders = ",".join(["%s"]*len(airport_df.columns))
query = f"insert into Airport({columns}) values({placeholders})"
tuple_data = []
for i in airport_df.index:
    row = list(airport_df.loc[i].values)
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()

## 2. Steps to collect aircraft data using API and convert into sql

In [115]:
#Defining a function with icao code
def fetch_aircraft_by_reg(reg_code):
    url=f"https://aerodatabox.p.rapidapi.com/aircrafts/reg/{reg_code}"
    response=requests.get(url,headers=headers)
    time.sleep(1)
    return response.json()

In [116]:
my_aircraft=['9V-MBV', '9V-MBU', '9V-SDC', 'PH-AXR', 'PH-AXN', 'PH-AXP', 'G-TTSG', 'G-TNEJ', 'G-TNEI', 'A7-BIA', 'A7-BTD', 'A7-BHZ', 'VT-AWA', 'VT-TNI', 'VT-TNM', 'A6-EWL', 'A6-EXR', 'A6-EWK']

aircraft_all={}

for REG_code in my_aircraft:
    try:
        aircraft_data=fetch_aircraft_by_reg(REG_code)
        aircraft_all[REG_code]=aircraft_data
        print(aircraft_data)
    except Exception as e:
        print(f"Error loading airport {REG_code}: {e}")

{'id': 2156998, 'reg': '9V-MBV', 'active': True, 'serial': '44260', 'hexIcao': '76B456', 'airlineName': 'Singapore Airlines', 'iataCodeShort': '7M8', 'icaoCode': 'B38M', 'model': 'B38M', 'modelCode': '737-8MAX', 'firstFlightDate': '2026-02-24', 'deliveryDate': '2026-04-05', 'registrationDate': '2026-04-05', 'typeName': 'Boeing 737 MAX 8', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 737 MAX', 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2156692, 'reg': '9V-MBU', 'active': True, 'serial': '44264', 'hexIcao': '76B455', 'airlineName': 'Singapore Airlines', 'iataCodeShort': '7M8', 'icaoCode': 'B38M', 'model': 'B38M', 'modelCode': '737-8MAX', 'deliveryDate': '2026-02-13', 'registrationDate': '2026-02-13', 'typeName': 'Boeing 737 MAX 8', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 737 MAX', 'ageYears': 0.3, 'verified': True, 'numRegistrations': 1}
{'id': 2156598, 'reg': '9V-SDC', 'active': True, 'serial': '36527', 'hexIcao': '76CC83', 'airlineName': 'Singapore Airlines', 'iataCodeShort': '781', 'icaoCode': 'B78X', 'model': 'B781', 'modelCode': '787-10', 'deliveryDate': '2026-01-25', 'registrationDate': '2026-01-25', 'typeName': 'Boeing 787-10', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 0.3, 'verified': True, 'numRegistrations': 1}
{'id': 2156583, 'reg': 'PH-AXR', 'active': True, 'serial': '13080', 'hexIcao': '4868F8', 'airlineName': 'KLM', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-252NX', 'numSeats': 227, 'firstFlightDate': '2026-02-27', 'deliveryDate': '2026-03-27', 'registrationDate': '2026-03-27', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2156577, 'reg': 'PH-AXN', 'active': True, 'serial': '12997', 'hexIcao': '4868BC', 'airlineName': 'KLM', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-252NX', 'numSeats': 227, 'deliveryDate': '2026-03-06', 'registrationDate': '2026-03-06', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2156629, 'reg': 'PH-AXP', 'active': True, 'serial': '13050', 'hexIcao': '4868F7', 'airlineName': 'KLM', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-252NX', 'numSeats': 227, 'firstFlightDate': '2026-02-16', 'deliveryDate': '2026-02-27', 'registrationDate': '2026-02-27', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.3, 'verified': True, 'numRegistrations': 1}
{'id': 2146113, 'reg': 'G-TTSG', 'active': True, 'serial': '12693', 'hexIcao': '40822E', 'airlineName': 'British Airways', 'iataCodeShort': '32N', 'icaoCode': 'A20N', 'model': 'A20N', 'modelCode': '320-251N', 'deliveryDate': '2025-10-20', 'registrationDate': '2025-10-20', 'typeName': 'Airbus A320 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320 NEO', 'ageYears': 0.6, 'verified': True, 'numRegistrations': 1}
{'id': 2146053, 'reg': 'G-TNEJ', 'active': True, 'serial': '12753', 'hexIcao': '408229', 'airlineName': 'British Airways', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-251NX', 'deliveryDate': '2025-10-09', 'registrationDate': '2025-10-09', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.6, 'verified': True, 'numRegistrations': 1}
{'id': 2146068, 'reg': 'G-TNEI', 'active': True, 'serial': '12706', 'hexIcao': '408228', 'airlineName': 'British Airways', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-251NX', 'deliveryDate': '2025-10-08', 'registrationDate': '2025-10-08', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.6, 'verified': True, 'numRegistrations': 1}
{'id': 2156943, 'reg': 'A7-BIA', 'active': True, 'serial': '64236', 'hexIcao': '06A2FE', 'airlineName': 'Qatar Airways', 'iataCodeShort': '789', 'icaoCode': 'B789', 'model': 'B789', 'modelCode': '787-9', 'firstFlightDate': '2026-03-06', 'deliveryDate': '2026-04-11', 'registrationDate': '2026-04-11', 'typeName': 'Boeing 787-9', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2156729, 'reg': 'A7-BTD', 'active': True, 'serial': '70442', 'hexIcao': '06A3B7', 'airlineName': 'Qatar Airways', 'modelCode': '777-F', 'deliveryDate': '2026-02-27', 'registrationDate': '2026-02-27', 'typeName': 'Boeing 777', 'isFreighter': True, 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2146485, 'reg': 'A7-BHZ', 'active': True, 'serial': '64235', 'hexIcao': '06A2FD', 'airlineName': 'Qatar Airways', 'iataCodeShort': '789', 'icaoCode': 'B789', 'model': 'B789', 'modelCode': '787-9', 'numSeats': 311, 'deliveryDate': '2025-12-29', 'registrationDate': '2025-12-29', 'typeName': 'Boeing 787-9', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 0.4, 'verified': True, 'numRegistrations': 1}
{'id': 2156528, 'reg': 'VT-AWA', 'active': True, 'serial': '69263', 'hexIcao': '8017F7', 'airlineName': 'Air India', 'iataCodeShort': '789', 'icaoCode': 'B789', 'model': 'B789', 'modelCode': '787-9', 'numSeats': 296, 'firstFlightDate': '2025-08-25', 'deliveryDate': '2026-01-09', 'registrationDate': '2026-01-09', 'typeName': 'Boeing 787-9', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 0.7, 'verified': True, 'numRegistrations': 1}
{'id': 53984, 'reg': 'VT-TNI', 'active': True, 'serial': '8099', 'hexIcao': '800C8F', 'airlineName': 'Air India', 'iataCodeShort': '32N', 'icaoCode': 'A20N', 'model': 'A20N', 'modelCode': '320-251N', 'numSeats': 164, 'rolloutDate': '2018-02-12', 'firstFlightDate': '2018-02-12', 'deliveryDate': '2018-03-01', 'registrationDate': '2024-11-11', 'typeName': 'Airbus A320 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320 NEO', 'ageYears': 8.3, 'verified': True, 'numRegistrations': 2}
{'id': 54241, 'reg': 'VT-TNM', 'active': True, 'serial': '9170', 'hexIcao': '800DB0', 'airlineName': 'Air India', 'iataCodeShort': '32N', 'icaoCode': 'A20N', 'model': 'A20N', 'modelCode': '320-251N', 'rolloutDate': '2019-11-01', 'firstFlightDate': '2019-11-01', 'deliveryDate': '2019-11-29', 'registrationDate': '2024-11-11', 'typeName': 'Airbus A320 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320 NEO', 'ageYears': 6.5, 'verified': True, 'numRegistrations': 2}
{'id': 2156756, 'reg': 'A6-EWL', 'active': True, 'serial': '70437', 'hexIcao': '8966EE', 'airlineName': 'Emirates', 'modelCode': '777-F', 'firstFlightDate': '2026-03-20', 'deliveryDate': '2026-03-31', 'registrationDate': '2026-03-31', 'typeName': 'Boeing 777', 'isFreighter': True, 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
{'id': 2156829, 'reg': 'A6-EXR', 'active': True, 'serial': '760', 'hexIcao': '896680', 'airlineName': 'Emirates', 'iataCodeShort': '359', 'icaoCode': 'A359', 'model': 'A359', 'modelCode': '350-941', 'numSeats': 298, 'firstFlightDate': '2026-01-26', 'deliveryDate': '2026-03-30', 'registrationDate': '2026-03-30', 'typeName': 'Airbus A350-900', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A350', 'ageYears': 0.3, 'verified': True, 'numRegistrations': 1}
{'id': 2156742, 'reg': 'A6-EWK', 'active': True, 'serial': '70436', 'hexIcao': '8966ED', 'airlineName': 'Emirates', 'modelCode': '777-F', 'deliveryDate': '2026-03-05', 'registrationDate': '2026-03-05', 'typeName': 'Boeing 777', 'isFreighter': True, 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}

In [156]:
import pandas as pd

def extract_aircraft_info(aircraft_data):
    extracted_aircraft_info = {
        'aircraft_code': aircraft_data.get('reg'),
        'aircraft_type': aircraft_data.get('typeName'),
        'serial': aircraft_data.get('serial'),
        'model': aircraft_data.get('model'),
        'airline': aircraft_data.get('airlineName'),
        'icao_code': aircraft_data.get('icaoCode'),
        'engine': aircraft_data.get('engineType'),
        }
    return extracted_aircraft_info

In [164]:
extracted_aircrafts_data = []
for aircraft_code, data in aircraft_all.items():
        extracted_aircrafts_data.append(extract_aircraft_info(data))

# Create a pandas DataFrame from the extracted data
aircraft_df = pd.DataFrame(extracted_aircrafts_data)
aircraft_df = aircraft_df.fillna("Unknown")
#aircraft_df_dropped = aircraft_df.dropna() #drops rows with null values since NaN and NaT are not accepteble in sql
display(aircraft_df)

,aircraft_code,aircraft_type,serial,model,airline,icao_code,engine
0,9V-MBV,Boeing 737 MAX 8,44260,B38M,Singapore Airlines,B38M,Jet
1,9V-MBU,Boeing 737 MAX 8,44264,B38M,Singapore Airlines,B38M,Jet
2,9V-SDC,Boeing 787-10,36527,B781,Singapore Airlines,B78X,Jet
3,PH-AXR,Airbus A321 NEO,13080,A21N,KLM,A21N,Jet
4,PH-AXN,Airbus A321 NEO,12997,A21N,KLM,A21N,Jet
5,PH-AXP,Airbus A321 NEO,13050,A21N,KLM,A21N,Jet
6,G-TTSG,Airbus A320 NEO,12693,A20N,British Airways,A20N,Jet
7,G-TNEJ,Airbus A321 NEO,12753,A21N,British Airways,A21N,Jet
8,G-TNEI,Airbus A321 NEO,12706,A21N,British Airways,A21N,Jet
9,A7-BIA,Boeing 787-9,64236,B789,Qatar Airways,B789,Jet
10,A7-BTD,Boeing 777,70442,Unknown,Qatar Airways,Unknown,Unknown
11,A7-BHZ,Boeing 787-9,64235,B789,Qatar Airways,B789,Jet
12,VT-AWA,Boeing 787-9,69263,B789,Air India,B789,Jet
13,VT-TNI,Airbus A320 NEO,8099,A20N,Air India,A20N,Jet
14,VT-TNM,Airbus A320 NEO,9170,A20N,Air India,A20N,Jet
15,A6-EWL,Boeing 777,70437,Unknown,Emirates,Unknown,Unknown
16,A6-EXR,Airbus A350-900,760,A359,Emirates,A359,Jet
17,A6-EWK,Boeing 777,70436,Unknown,Emirates,Unknown,Unknown

In [158]:
aircraft_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   aircraft_code  18 non-null     str
 1   aircraft_type  18 non-null     str
 2   serial         18 non-null     str
 3   model          18 non-null     str
 4   airline        18 non-null     str
 5   icao_code      18 non-null     str
 6   engine         18 non-null     str
dtypes: str(7)
memory usage: 1.1 KB

In [167]:
query = """create table if not exists Aircrafts(aircraft_id int primary key AUTO_INCREMENT, aircraft_code varchar(60) UNIQUE, aircraft_type varchar(60), serial varchar(60), model varchar(60), airline varchar(60), icao_code varchar(60), engine varchar(60))"""
cursor.execute(query)
connection.commit()

In [168]:
columns = ",".join(aircraft_df.columns)
placeholders = ",".join(["%s"]*len(aircraft_df.columns))
query = f"insert into Aircrafts({columns}) values({placeholders})"
tuple_data = []
for i in aircraft_df.index:
    row = list(aircraft_df.loc[i].values)
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()