# Data Extraction and Storage

## 1. Steps to collect airport data using API and convert into SQL

In [2]:
import time
import pandas as pd

In [87]:
#Connection to the url with key
import requests
API_HOST = "aerodatabox.p.rapidapi.com"
API_KEY = "ae6852a1abmshff7e7a387a1f740p1da32ejsn8af8b9de9fbd"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": API_HOST
}

In [ ]:
#Defining a function with icao code
def fetch_airport_by_icao(icao_code):
    url=f"https://aerodatabox.p.rapidapi.com/airports/icao/{icao_code}"
    airport_response=requests.get(url,headers=headers)
    time.sleep(1)
    return airport_response.json()

In [ ]:
my_airports=["EGLL", "KJFK", "OMDB", "VIDP", "VOBL", "EGCC", "EDDM", "CYVR", "RJOO", "WMKP", "VTCC", "EHAM", "LFPG", "WSSS", "YSSY"]

airport_all={}

for icao in my_airports:
    try:
        airport_data=fetch_airport_by_icao(icao)
        airport_all[icao]=airport_data
        print(airport_data)
    except Exception as e:
        print(f"Error loading airport {icao}: {e}")

{'icao': 'EGLL', 'iata': 'LHR', 'shortName': 'Heathrow', 'fullName': 'London Heathrow', 'municipalityName': 'London', 'location': {'lat': 51.4706, 'lon': -0.461941}, 'elevation': {'meter': 25.3, 'km': 0.03, 'mile': 0.02, 'nm': 0.01, 'feet': 83.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.heathrow.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/London_Heathrow_Airport', 'twitter': 'https://x.com/HeathrowAirport', 'flightRadar': 'https://www.flightradar24.com/51.47,-0.46/14', 'googleMaps': 'https://www.google.com/maps/@51.470600,-0.461941,14z'}}
{'icao': 'KJFK', 'iata': 'JFK', 'shortName': 'John F Kennedy', 'fullName': 'New York John F Kennedy', 'municipalityName': 'New York', 'location': {'lat': 40.6398, 'lon': -73.7789}, 'elevation': {'meter': 3.96, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 13.0}, 'country': {'code': 'US', 'name': 'United States'}, 'continent': {'code': 'NA', 'name': 'North America'}, 'timeZone': 'America/New_York', 'urls': {'webSite': 'http://www.panynj.gov/airports/jfk.html', 'wikipedia': 'https://en.wikipedia.org/wiki/John_F._Kennedy_International_Airport', 'twitter': 'https://x.com/JFKairport', 'liveAtc': 'https://www.liveatc.net/search/?icao=KJFK', 'flightRadar': 'https://www.flightradar24.com/40.64,-73.78/14', 'googleMaps': 'https://www.google.com/maps/@40.639801,-73.778900,14z'}}
{'icao': 'OMDB', 'iata': 'DXB', 'shortName': 'Dubai', 'fullName': 'Dubai', 'municipalityName': 'Dubai', 'location': {'lat': 25.252798, 'lon': 55.3644}, 'elevation': {'meter': 18.9, 'km': 0.02, 'mile': 0.01, 'nm': 0.01, 'feet': 62.0}, 'country': {'code': 'AE', 'name': 'United Arab Emirates'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Dubai', 'urls': {'webSite': 'http://www.dubaiairports.ae/', 'wikipedia': 'https://en.wikipedia.org/wiki/Dubai_International_Airport', 'twitter': 'https://x.com/DubaiAirports', 'flightRadar': 'https://www.flightradar24.com/25.25,55.36/14', 'googleMaps': 'https://www.google.com/maps/@25.252799,55.364398,14z'}}
{'icao': 'VIDP', 'iata': 'DEL', 'shortName': 'Indira Gandhi', 'fullName': 'New Delhi Indira Gandhi', 'municipalityName': 'New Delhi', 'location': {'lat': 28.5665, 'lon': 77.1031}, 'elevation': {'meter': 236.83, 'km': 0.24, 'mile': 0.15, 'nm': 0.13, 'feet': 777.0}, 'country': {'code': 'IN', 'name': 'India'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kolkata', 'urls': {'webSite': 'http://www.newdelhiairport.in/', 'wikipedia': 'https://en.wikipedia.org/wiki/Indira_Gandhi_International_Airport', 'flightRadar': 'https://www.flightradar24.com/28.57,77.10/14', 'googleMaps': 'https://www.google.com/maps/@28.566499,77.103103,14z'}}
{'icao': 'VOBL', 'iata': 'BLR', 'shortName': 'Bengaluru', 'fullName': 'Bangalore Bengaluru', 'municipalityName': 'Bangalore', 'location': {'lat': 13.197899, 'lon': 77.7063}, 'elevation': {'meter': 914.4, 'km': 0.91, 'mile': 0.57, 'nm': 0.49, 'feet': 3000.0}, 'country': {'code': 'IN', 'name': 'India'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kolkata', 'urls': {'webSite': 'https://www.bengaluruairport.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/Bengaluru_International_Airport', 'twitter': 'https://x.com/BLRAirport', 'flightRadar': 'https://www.flightradar24.com/13.20,77.71/14', 'googleMaps': 'https://www.google.com/maps/@13.197899,77.706298,14z'}}
{'icao': 'EGCC', 'iata': 'MAN', 'shortName': 'Manchester', 'fullName': 'Manchester', 'municipalityName': 'Manchester', 'location': {'lat': 53.3537, 'lon': -2.27495}, 'elevation': {'meter': 78.33, 'km': 0.08, 'mile': 0.05, 'nm': 0.04, 'feet': 257.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.manchesterairport.co.uk/', 'wikipedia': 'https://en.wikipedia.org/wiki/Manchester_Airport', 'twitter': 'https://x.com/manairport', 'flightRadar': 'https://www.flightradar24.com/53.35,-2.27/14', 'googleMaps': 'https://www.google.com/maps/@53.353698,-2.274950,14z'}}
{'icao': 'EDDM', 'iata': 'MUC', 'shortName': 'Munich', 'fullName': 'Munich', 'municipalityName': 'Munich', 'location': {'lat': 48.3538, 'lon': 11.7861}, 'elevation': {'meter': 453.24, 'km': 0.45, 'mile': 0.28, 'nm': 0.24, 'feet': 1487.0}, 'country': {'code': 'DE', 'name': 'Germany'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Berlin', 'urls': {'webSite': 'http://www.munich-airport.de/', 'wikipedia': 'https://en.wikipedia.org/wiki/Munich_International_Airport', 'twitter': 'https://x.com/MUC_Airport', 'flightRadar': 'https://www.flightradar24.com/48.35,11.79/14', 'googleMaps': 'https://www.google.com/maps/@48.353801,11.786100,14z'}}
{'icao': 'CYVR', 'iata': 'YVR', 'shortName': 'Vancouver', 'fullName': 'Vancouver', 'municipalityName': 'Vancouver', 'location': {'lat': 49.1939, 'lon': -123.184}, 'elevation': {'meter': 4.27, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 14.0}, 'country': {'code': 'CA', 'name': 'Canada'}, 'continent': {'code': 'NA', 'name': 'North America'}, 'timeZone': 'America/Vancouver', 'urls': {'webSite': 'http://www.yvr.ca/', 'wikipedia': 'https://en.wikipedia.org/wiki/Vancouver_International_Airport', 'twitter': 'https://x.com/yvrairport', 'liveAtc': 'https://www.liveatc.net/search/?icao=CYVR', 'flightRadar': 'https://www.flightradar24.com/49.19,-123.18/14', 'googleMaps': 'https://www.google.com/maps/@49.193901,-123.183998,14z'}}
{'icao': 'RJOO', 'iata': 'ITM', 'shortName': 'Osaka', 'fullName': 'Osaka', 'municipalityName': 'Osaka', 'location': {'lat': 34.7855, 'lon': 135.438}, 'elevation': {'meter': 15.24, 'km': 0.02, 'mile': 0.01, 'nm': 0.01, 'feet': 50.0}, 'country': {'code': 'JP', 'name': 'Japan'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Tokyo', 'urls': {'webSite': 'https://www.osaka-airport.co.jp/', 'wikipedia': 'https://en.wikipedia.org/wiki/Osaka_International_Airport', 'liveAtc': 'https://www.liveatc.net/search/?icao=RJOO', 'flightRadar': 'https://www.flightradar24.com/34.79,135.44/14', 'googleMaps': 'https://www.google.com/maps/@34.785499,135.438003,14z'}}
{'icao': 'WMKP', 'iata': 'PEN', 'shortName': 'Penang', 'fullName': 'Penang', 'municipalityName': 'Penang', 'location': {'lat': 5.29714, 'lon': 100.277}, 'elevation': {'meter': 3.35, 'km': 0.0, 'mile': 0.0, 'nm': 0.0, 'feet': 11.0}, 'country': {'code': 'MY', 'name': 'Malaysia'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Kuala_Lumpur', 'urls': {'webSite': 'https://airports.malaysiaairports.com.my/', 'wikipedia': 'https://en.wikipedia.org/wiki/Penang_International_Airport', 'twitter': 'https://x.com/MY_Airports', 'flightRadar': 'https://www.flightradar24.com/5.30,100.28/14', 'googleMaps': 'https://www.google.com/maps/@5.297140,100.277000,14z'}}
{'icao': 'VTCC', 'iata': 'CNX', 'shortName': 'Chiang Mai', 'fullName': 'Chiangmai Chiang Mai', 'municipalityName': 'Chiangmai', 'location': {'lat': 18.7668, 'lon': 98.9626}, 'elevation': {'meter': 315.77, 'km': 0.32, 'mile': 0.2, 'nm': 0.17, 'feet': 1036.0}, 'country': {'code': 'TH', 'name': 'Thailand'}, 'continent': {'code': 'AS', 'name': 'Asia'}, 'timeZone': 'Asia/Bangkok', 'urls': {'webSite': 'https://chiangmai.airportthai.co.th/', 'wikipedia': 'https://en.wikipedia.org/wiki/Chiang_Mai_International_Airport', 'twitter': 'https://x.com/AOTthailand', 'flightRadar': 'https://www.flightradar24.com/18.77,98.96/14', 'googleMaps': 'https://www.google.com/maps/@18.766799,98.962600,14z'}}
{'icao': 'EHAM', 'iata': 'AMS', 'shortName': 'Schiphol', 'fullName': 'Amsterdam Schiphol', 'municipalityName': 'Amsterdam', 'location': {'lat': 52.3086, 'lon': 4.763889}, 'elevation': {'meter': -3.35, 'km': -0.0, 'mile': -0.0, 'nm': -0.0, 'feet': -11.0}, 'country': {'code': 'NL', 'name': 'Netherlands'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Amsterdam', 'urls': {'webSite': 'http://www.schiphol.nl/', 'wikipedia': 'https://en.wikipedia.org/wiki/Amsterdam_Schiphol_Airport', 'twitter': 'https://x.com/Schiphol', 'liveAtc': 'https://www.liveatc.net/search/?icao=EHAM', 'flightRadar': 'https://www.flightradar24.com/52.31,4.76/14', 'googleMaps': 'https://www.google.com/maps/@52.308601,4.763889,14z'}}
{'icao': 'LFPG', 'iata': 'CDG', 'shortName': 'Charles de Gaulle', 'fullName': 'Paris Charles de Gaulle', 'municipalityName': 'Paris', 'location': {'lat': 49.0128, 'lon': 2.549999}, 'elevation': {'meter': 119.48, 'km': 0.12, 'mile': 0.07, 'nm': 0.06, 'feet': 392.0}, 'country': {'code': 'FR', 'name': 'France'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/Paris', 'urls': {'webSite': 'http://www.parisaeroport.fr/', 'wikipedia': 'https://en.wikipedia.org/wiki/Charles_de_Gaulle_International_Airport', 'twitter': 'https://x.com/ParisAeroport', 'liveAtc': 'https://www.liveatc.net/search/?icao=LFPG', 'flightRadar': 'https://www.flightradar24.com/49.01,2.55/14', 'googleMaps': 'https://www.google.com/maps/@49.012798,2.549999,14z'}}

In [10]:


def extract_airport_info(airport_data):
    extracted_info = {
        'icao_code': airport_data.get('icao'),
        'iata_code': airport_data.get('iata'),
        'name': airport_data.get('fullName'),
        'city': airport_data.get('municipalityName'),
        'country': airport_data.get('country', {}).get('name'),
        'continent': airport_data.get('continent', {}).get('name'),
        'latitude': airport_data.get('location', {}).get('lat'),
        'longitude': airport_data.get('location', {}).get('lon'),
        'timezone': airport_data.get('timeZone')
    }
    return extracted_info

In [ ]:
extracted_airports_data = []
for icao, data in airport_all.items():
    extracted_airports_data.append(extract_airport_info(data))

# Create a pandas DataFrame from the extracted data
airport_df = pd.DataFrame(extracted_airports_data)
display(airport_df)

NameError: name 'airport_all' is not defined

In [3]:
#To make a connection to mysql
import mysql.connector 

connection = mysql.connector.connect(
    host = "Localhost",
    user = "root",
    password = "12345",
    )
cursor =  connection.cursor()
cursor

In [ ]:
query="create database if not exists AeroDataBox"
cursor.execute(query)
connection.commit()

In [4]:
query = "use AeroDataBox"
cursor.execute(query)

In [ ]:
query = """create table if not exists Airport(airport_id int primary key auto_increment, icao_code varchar(60) UNIQUE, iata_code varchar(60) UNIQUE, name varchar(60), city varchar(60), country varchar(60), continent varchar(60), latitude float, longitude float, timezone varchar(60))"""
cursor.execute(query)
connection.commit()

In [ ]:
columns = ",".join(airport_df.columns)
placeholders = ",".join(["%s"]*len(airport_df.columns))
query = f"insert ignore into Airport({columns}) values({placeholders})"
tuple_data = []
for i in airport_df.index:
    row = list(airport_df.loc[i].values)
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()

## 2. Steps to collect flight data using API and convert into SQL

In [88]:
#Defining a function with icao code
def fetch_flight_by_icao(icao_code):
    url=f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/{icao_code}/2026-05-17T20:00/2026-05-18T08:00"
    querystring = {"withLeg":"true","direction":"Both","withCancelled":"true","withCodeshared":"true","withCargo":"true","withPrivate":"true","withLocation":"false"}

    flight_response=requests.get(url,headers=headers, params=querystring)
    time.sleep(1)
    return flight_response.json()

In [92]:
def extract_flight_info(flight_data, flight_type, airport_icao):
    flight_id = flight_data.get('number', '') + '_' + flight_data.get(flight_type, {}).get('scheduledTime', {}).get('utc', '')

    # Determine origin and destination based on flight type, ensuring ICAO codes
    origin_code = ''
    destination_code = ''
    if flight_type == 'departure':
        origin_code = airport_icao # The airport from which the flights were fetched
        destination_code = flight_data.get('arrival', {}).get('airport', {}).get('icao')
    elif flight_type == 'arrival':
        origin_code = flight_data.get('departure', {}).get('airport', {}).get('icao')
        destination_code = airport_icao # The airport to which the flights were fetched

    return {
        'flight_id': flight_id,
        'flight_number': flight_data.get('number'),
        'aircraft_registration': flight_data.get('aircraft', {}).get('reg'),
        'origin_icao': origin_code,
        'destination_icao': destination_code,
        'scheduled_departure': flight_data.get('departure', {}).get('scheduledTime', {}).get('utc', ''),
        'actual_departure': flight_data.get('departure', {}).get('revisedTime', {}).get('utc', flight_data.get('departure', {}).get('scheduledTime', {}).get('utc')),#fallback extraction
        'scheduled_arrival': flight_data.get('arrival', {}).get('scheduledTime', {}).get('utc'),
        'actual_arrival': flight_data.get('arrival', {}).get('revisedTime', {}).get('utc', flight_data.get('arrival', {}).get('scheduledTime', {}).get('utc')),
        'status': flight_data.get('status'),
        'airline_code': flight_data.get('airline', {}).get('iata')
    }

In [ ]:
all_flights_data = []
list_icao = airport_df['icao_code']
flights_all={}
for icao in list_icao:
    try:
        airflight_data=fetch_flight_by_icao(icao)
        flight_all[icao] = airflight_data
        print(flight_all[icao])
    except Exception as e:
        print(f"Error loading flight {icao}: {e}")

Error loading flight EGLL: name 'flight_all' is not defined
Error loading flight KJFK: name 'flight_all' is not defined
Error loading flight OMDB: name 'flight_all' is not defined
Error loading flight VIDP: name 'flight_all' is not defined
Error loading flight VOBL: name 'flight_all' is not defined
Error loading flight EGCC: name 'flight_all' is not defined
Error loading flight EDDM: name 'flight_all' is not defined
Error loading flight CYVR: name 'flight_all' is not defined
Error loading flight RJOO: name 'flight_all' is not defined
Error loading flight WMKP: name 'flight_all' is not defined
Error loading flight VTCC: name 'flight_all' is not defined
Error loading flight EHAM: name 'flight_all' is not defined

In [ ]:
for icao in list_icao:
    # Get current airport data
        curr_airport_data = flight_all[icao]
    # Extract departures
        if 'departures' in curr_airport_data:
            for flight in curr_airport_data.get('departures',[])[:20]:
                all_flights_data.append(extract_flight_info(flight, 'departure', icao)) 

# Extract arrivals
        if 'arrivals' in curr_airport_data:
            for flight in curr_airport_data.get('arrivals',[])[:20]:
                all_flights_data.append(extract_flight_info(flight, 'arrival', icao))
    
# Create DataFrame
flights_df = pd.DataFrame(all_flights_data)
display(flights_df)

,flight_id,flight_number,aircraft_registration,origin_icao,destination_icao,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,status,airline_code
0,AY 5945_2026-05-17 18:00Z,AY 5945,G-XLED,EGLL,FAOR,2026-05-17 18:00Z,2026-05-17 19:00Z,2026-05-18 05:00Z,2026-05-18 05:04Z,Departed,AY
1,BA 55_2026-05-17 18:00Z,BA 55,G-XLED,EGLL,FAOR,2026-05-17 18:00Z,2026-05-17 19:00Z,2026-05-18 05:00Z,2026-05-18 05:04Z,Departed,BA
2,AA 7106_2026-05-17 18:00Z,AA 7106,G-XLED,EGLL,FAOR,2026-05-17 18:00Z,2026-05-17 19:00Z,2026-05-18 05:00Z,2026-05-18 05:04Z,Departed,AA
3,IB 3511_2026-05-17 18:00Z,IB 3511,G-XLED,EGLL,FAOR,2026-05-17 18:00Z,2026-05-17 19:00Z,2026-05-18 05:00Z,2026-05-18 05:04Z,Departed,IB
4,KE 908_2026-05-17 18:35Z,KE 908,HL7203,EGLL,RKSI,2026-05-17 18:35Z,2026-05-17 19:02Z,2026-05-18 07:15Z,2026-05-18 06:58Z,Departed,KE
...,...,...,...,...,...,...,...,...,...,...,...
595,CI 8390_2026-05-17 10:00Z,CI 8390,NaN,NaN,YSSY,,NaN,2026-05-17 10:00Z,2026-05-17 10:14Z,Arrived,CI
596,VA 986_2026-05-17 10:40Z,VA 986,VH-IJU,YBBN,YSSY,2026-05-17 09:05Z,2026-05-17 09:00Z,2026-05-17 10:40Z,2026-05-17 10:18Z,Arrived,VA
597,QF 2183_2026-05-17 10:50Z,QF 2183,VH-QOD,YMOR,YSSY,2026-05-17 09:20Z,2026-05-17 09:20Z,2026-05-17 10:50Z,2026-05-17 10:20Z,Arrived,QF
598,NZ 7451_2026-05-17 10:50Z,NZ 7451,NaN,NaN,YSSY,,NaN,2026-05-17 10:50Z,2026-05-17 10:20Z,Arrived,NZ
599,JQ 40_2026-05-17 10:15Z,JQ 40,VH-OFL,WADD,YSSY,2026-05-17 04:20Z,2026-05-17 04:20Z,2026-05-17 10:15Z,2026-05-17 10:25Z,Arrived,JQ

In [ ]:
flights_df=flights_df.fillna("None")
flights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   flight_id              600 non-null    str
 1   flight_number          600 non-null    str
 2   aircraft_registration  600 non-null    str
 3   origin_icao            600 non-null    str
 4   destination_icao       600 non-null    str
 5   scheduled_departure    600 non-null    str
 6   actual_departure       600 non-null    str
 7   scheduled_arrival      600 non-null    str
 8   actual_arrival         600 non-null    str
 9   status                 600 non-null    str
 10  airline_code           600 non-null    str
dtypes: str(11)
memory usage: 51.7 KB

In [ ]:
query="""create table if not exists flight(flight_id varchar(60) PRIMARY KEY, flight_number varchar(60), aircraft_registration varchar(60), origin_icao varchar(60), destination_icao varchar(60), scheduled_departure varchar(60), actual_departure varchar(60), scheduled_arrival varchar(60), actual_arrival varchar(60), status varchar(60), airline_code varchar(60))"""
cursor.execute(query)

In [84]:
columns = ",".join(flights_df.columns)
placeholders = ",".join(["%s"]*len(flights_df.columns))
query = f"insert into flight({columns}) values({placeholders})"
tuple_data = []
for i in flights_df.index:
    row = list(flights_df.loc[i].values)
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()

NameError: name 'flights_df' is not defined

In [83]:
list_aircraft=flights_df['aircraft_registration'].unique().tolist()#294 entries
cleanlist_aircraft=[x for x in list_aircraft if x != "None"]
cleanlist_aircraft

NameError: name 'flights_df' is not defined

## 3. Steps to collect aircraft data using API and convert into SQL

In [ ]:
#Defining a function with icao code
def fetch_aircraft_by_reg(reg_code):
    url=f"https://aerodatabox.p.rapidapi.com/aircrafts/reg/{reg_code}"
    aircraft_response=requests.get(url,headers=headers)
    time.sleep(1)
    return aircraft_response.json()

In [ ]:
aircraft_all={}

for REG_code in cleanlist_aircraft[:100]:
    try:
        aircraft_data=fetch_aircraft_by_reg(REG_code)
        aircraft_all[REG_code]=aircraft_data
        print(REG_code, aircraft_all[REG_code])
    except Exception as e:
        print(f"Error loading airport {REG_code}: {e}")

G-XLED {'id': 1920, 'reg': 'G-XLED', 'active': True, 'serial': '144', 'hexIcao': '406A03', 'airlineName': 'British Airways', 'iataCodeShort': '388', 'icaoCode': 'A388', 'model': 'A388', 'modelCode': '380-841', 'numSeats': 469, 'rolloutDate': '2013-08-01', 'firstFlightDate': '2013-08-01', 'deliveryDate': '2014-01-17', 'registrationDate': '2014-01-17', 'typeName': 'Airbus A380-800', 'numEngines': 4, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A380', 'ageYears': 12.8, 'verified': True, 'numRegistrations': 1}
HL7203 {'id': 23455, 'reg': 'HL7203', 'active': True, 'serial': '60378', 'hexIcao': '71BA03', 'airlineName': 'Korean Air', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': 'B773', 'modelCode': 'B777-3B5ER', 'numSeats': 277, 'rolloutDate': '2018-02-06', 'firstFlightDate': '2018-02-07', 'deliveryDate': '2018-03-20', 'registrationDate': '2018-03-20', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 8.3, 'verified': True, 'numRegistrations': 1}
G-EUYV {'id': 23628, 'reg': 'G-EUYV', 'active': True, 'serial': '6091', 'hexIcao': '406AE2', 'airlineName': 'British Airways', 'iataCodeShort': '32A', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 180, 'rolloutDate': '2014-04-22', 'firstFlightDate': '2014-04-22', 'deliveryDate': '2014-05-16', 'registrationDate': '2014-05-15', 'typeName': 'Airbus A320 (Sharklets)', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 12.1, 'verified': True, 'numRegistrations': 1}
D-AGWV {'id': 22126, 'reg': 'D-AGWV', 'active': True, 'serial': '5467', 'hexIcao': '3C5EF6', 'airlineName': 'Eurowings', 'iataCodeShort': '319', 'icaoCode': 'A319', 'model': 'A319', 'modelCode': '319-132', 'numSeats': 150, 'rolloutDate': '2013-02-06', 'firstFlightDate': '2013-02-06', 'deliveryDate': '2013-02-15', 'registrationDate': '2017-10-28', 'typeName': 'Airbus A319', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A319', 'ageYears': 13.3, 'verified': True, 'numRegistrations': 2}
EI-SIA {'id': 26581, 'reg': 'EI-SIA', 'active': True, 'serial': '7897', 'hexIcao': '4CACB4', 'airlineName': 'SAS Ireland', 'iataCodeShort': '32B', 'icaoCode': 'A321', 'model': 'A20N', 'modelCode': '320-251N', 'numSeats': 180, 'rolloutDate': '2017-11-24', 'firstFlightDate': '2017-11-24', 'deliveryDate': '2017-11-30', 'registrationDate': '2021-10-07', 'typeName': 'Airbus A321 (Sharklets)', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321', 'ageYears': 8.5, 'verified': True, 'numRegistrations': 3}
G-EUYC {'id': 15163, 'reg': 'G-EUYC', 'active': True, 'serial': '3721', 'hexIcao': '405EE0', 'airlineName': 'British Airways', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 180, 'rolloutDate': '2008-11-25', 'firstFlightDate': '2008-11-25', 'deliveryDate': '2008-12-12', 'registrationDate': '2008-12-12', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 17.5, 'verified': True, 'numRegistrations': 1}
B-2021 {'id': 19005, 'reg': 'B-2021', 'active': True, 'serial': '43273', 'hexIcao': '780D9D', 'airlineName': 'China Eastern Airlines', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': 'B773', 'modelCode': 'B777-39PER', 'numSeats': 316, 'rolloutDate': '2015-05-22', 'firstFlightDate': '2015-05-22', 'deliveryDate': '2015-06-23', 'registrationDate': '2015-06-23', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 11.0, 'verified': True, 'numRegistrations': 1}
G-EUUA {'id': 3064, 'reg': 'G-EUUA', 'active': True, 'serial': '1661', 'hexIcao': '40097C', 'airlineName': 'British Airways', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 180, 'rolloutDate': '2001-11-19', 'firstFlightDate': '2001-11-19', 'deliveryDate': '2002-01-31', 'registrationDate': '2002-01-31', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 24.5, 'verified': True, 'numRegistrations': 1}
4X-EDA {'id': 24407, 'reg': '4X-EDA', 'active': True, 'serial': '63548', 'hexIcao': '7380C0', 'airlineName': 'El Al', 'iataCodeShort': '789', 'icaoCode': 'B789', 'model': 'B789', 'modelCode': 'B787-9', 'numSeats': 282, 'rolloutDate': '2017-07-11', 'firstFlightDate': '2017-07-12', 'deliveryDate': '2017-08-22', 'registrationDate': '2017-08-23', 'typeName': 'Boeing 787-9', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 8.9, 'verified': True, 'numRegistrations': 1}
G-TTNL {'id': 31651, 'reg': 'G-TTNL', 'active': True, 'serial': '9585', 'hexIcao': '40792F', 'airlineName': 'British Airways', 'iataCodeShort': '32N', 'icaoCode': 'A20N', 'model': 'A20N', 'modelCode': '320-251N', 'numSeats': 180, 'rolloutDate': '2020-02-28', 'registrationDate': '2020-03-09', 'typeName': 'Airbus A320 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320 NEO', 'ageYears': 6.2, 'verified': True, 'numRegistrations': 1}
N414YX {'id': 3371, 'reg': 'N414YX', 'active': True, 'serial': '17000377', 'hexIcao': 'A4E538', 'airlineName': 'Republic Airways', 'iataCodeShort': 'E75', 'icaoCode': 'E175', 'model': 'E175', 'modelCode': '175LR', 'numSeats': 12, 'rolloutDate': '2013-11-08', 'deliveryDate': '2013-11-21', 'registrationDate': '2013-11-22', 'typeName': 'Embraer 175', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Embraer ERJ170', 'ageYears': 12.5, 'verified': True, 'numRegistrations': 1}
N815NW {'id': 26946, 'reg': 'N815NW', 'active': True, 'serial': '817', 'hexIcao': 'AB1D30', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '330', 'icaoCode': 'A330', 'model': 'A333', 'modelCode': '330-323X', 'numSeats': 293, 'rolloutDate': '2007-01-19', 'firstFlightDate': '2007-01-19', 'deliveryDate': '2007-02-22', 'registrationDate': '2010-01-05', 'typeName': 'Airbus A330', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A330', 'ageYears': 19.3, 'verified': True, 'numRegistrations': 2}
N390DA {'id': 10472, 'reg': 'N390DA', 'active': True, 'serial': '30536', 'hexIcao': 'A48315', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '738', 'icaoCode': 'B738', 'model': 'B738', 'modelCode': 'B737-832', 'rolloutDate': '2000-03-18', 'firstFlightDate': '2000-03-18', 'deliveryDate': '2000-03-24', 'registrationDate': '2000-04-28', 'typeName': 'Boeing 737-800', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 737 NG', 'ageYears': 26.2, 'verified': True, 'numRegistrations': 2}
HZ-AK36 {'id': 23847, 'reg': 'HZ-AK36', 'active': True, 'serial': '61599', 'hexIcao': '7100C8', 'airlineName': 'Saudi Arabian Airlines', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': 'B773', 'modelCode': 'B777-3FGER', 'numSeats': 290, 'rolloutDate': '2016-10-05', 'firstFlightDate': '2016-10-05', 'deliveryDate': '2016-11-09', 'registrationDate': '2016-11-09', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 9.6, 'verified': True, 'numRegistrations': 1}
G-VIIV {'id': 9955, 'reg': 'G-VIIV', 'active': True, 'serial': '29964', 'hexIcao': '400773', 'airlineName': 'British Airways', 'iataCodeShort': '772', 'icaoCode': 'B772', 'model': 'B772', 'modelCode': 'B777-236ER', 'numSeats': 236, 'rolloutDate': '1999-06-22', 'firstFlightDate': '1999-06-22', 'deliveryDate': '1999-06-29', 'registrationDate': '1999-06-29', 'typeName': 'Boeing 777-200', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 26.9, 'verified': True, 'numRegistrations': 1}
PH-BVF {'id': 16965, 'reg': 'PH-BVF', 'active': True, 'serial': '39972', 'hexIcao': '484CBA', 'airlineName': 'KLM', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': 'B773', 'modelCode': 'B777-306ER', 'numSeats': 408, 'rolloutDate': '2011-01-17', 'firstFlightDate': '2011-01-17', 'deliveryDate': '2011-02-07', 'registrationDate': '2011-02-07', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 15.3, 'verified': True, 'numRegistrations': 1}
N836DN {'id': 11279, 'reg': 'N836DN', 'active': True, 'serial': '31947', 'hexIcao': 'AB6EFC', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '737', 'model': 'B739', 'modelCode': 'B737-932ER', 'numSeats': 180, 'rolloutDate': '2015-03-05', 'firstFlightDate': '2015-03-05', 'deliveryDate': '2015-03-19', 'registrationDate': '2015-03-19', 'typeName': 'Boeing 737', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 737', 'ageYears': 11.2, 'verified': True, 'numRegistrations': 1}
N613JB {'id': 6157, 'reg': 'N613JB', 'active': True, 'serial': '2449', 'hexIcao': 'A7FAAD', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 150, 'rolloutDate': '2005-04-30', 'firstFlightDate': '2005-04-30', 'deliveryDate': '2005-06-15', 'registrationDate': '2005-06-16', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 21.1, 'verified': True, 'numRegistrations': 1}
N106NN {'id': 23158, 'reg': 'N106NN', 'active': True, 'serial': '5932', 'hexIcao': 'A01C37', 'airlineName': 'American Airlines', 'iataCodeShort': '32B', 'icaoCode': 'A321', 'model': 'A321', 'modelCode': '321-231', 'numSeats': 102, 'rolloutDate': '2014-01-10', 'firstFlightDate': '2014-01-10', 'deliveryDate': '2014-01-24', 'registrationDate': '2014-01-24', 'typeName': 'Airbus A321 (Sharklets)', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321', 'ageYears': 12.4, 'verified': True, 'numRegistrations': 1}
G-VUFO {'id': 1676, 'reg': 'G-VUFO', 'active': True, 'serial': '1352', 'hexIcao': '40683E', 'airlineName': 'Virgin Atlantic', 'iataCodeShort': '333', 'icaoCode': 'A333', 'model': 'A333', 'modelCode': '330-343X', 'numSeats': 264, 'rolloutDate': '2012-09-26', 'firstFlightDate': '2012-09-26', 'deliveryDate': '2012-11-15', 'registrationDate': '2012-11-15', 'typeName': 'Airbus A330-300', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A330', 'ageYears': 13.6, 'verified': True, 'numRegistrations': 1}
CC-BBH {'id': 18559, 'reg': 'CC-BBH', 'active': True, 'serial': '42224', 'hexIcao': 'E80200', 'airlineName': 'LATAM Chile', 'iataCodeShort': '788', 'icaoCode': 'B788', 'model': 'B788', 'modelCode': 'B787-8', 'numSeats': 247, 'rolloutDate': '2014-08-25', 'firstFlightDate': '2014-08-25', 'deliveryDate': '2014-09-10', 'registrationDate': '2016-05-05', 'typeName': 'Boeing 787-8', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 11.7, 'verified': True, 'numRegistrations': 2}
N485PX {'id': 2116940, 'reg': 'N485PX', 'active': True, 'serial': '15485', 'hexIcao': 'A5FC87', 'airlineName': 'Endeavor Air', 'iataCodeShort': 'CR9', 'icaoCode': 'CRJ9', 'model': 'CRJ9', 'modelCode': 'CRJ-900LR', 'numSeats': 76, 'rolloutDate': '2020-07-22', 'registrationDate': '2020-09-28', 'typeName': 'Canadair CRJ 900', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Canadair CRJ 900', 'ageYears': 5.8, 'verified': True, 'numRegistrations': 1}
TC-LJI {'id': 19329, 'reg': 'TC-LJI', 'active': True, 'serial': '44130', 'hexIcao': '4BB149', 'airlineName': 'Turkish Airlines', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': 'B773', 'modelCode': 'B777-3F2ER', 'numSeats': 349, 'rolloutDate': '2016-05-27', 'firstFlightDate': '2016-05-27', 'deliveryDate': '2016-06-16', 'registrationDate': '2016-06-16', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 777', 'ageYears': 10.0, 'verified': True, 'numRegistrations': 1}
N523DE {'id': 2122467, 'reg': 'N523DE', 'active': True, 'serial': '11236', 'hexIcao': 'A69463', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-271NX', 'numSeats': 194, 'deliveryDate': '2023-05-05', 'registrationDate': '2023-05-05', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 3.0, 'verified': True, 'numRegistrations': 1}
N602DZ {'id': 2156710, 'reg': 'N602DZ', 'active': True, 'serial': '12758', 'hexIcao': 'A7CF10', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-271NX', 'deliveryDate': '2026-02-28', 'registrationDate': '2026-02-28', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 0.2, 'verified': True, 'numRegistrations': 1}
N538DN {'id': 2122735, 'reg': 'N538DN', 'active': True, 'serial': '11436', 'hexIcao': 'A6CE7D', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '32Q', 'icaoCode': 'A21N', 'model': 'A21N', 'modelCode': '321-271NX', 'deliveryDate': '2023-06-23', 'registrationDate': '2023-06-23', 'typeName': 'Airbus A321 NEO', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321 NEO', 'ageYears': 2.9, 'verified': True, 'numRegistrations': 1}
N834AA {'id': 17405, 'reg': 'N834AA', 'active': True, 'serial': '40653', 'hexIcao': 'AB6737', 'airlineName': 'American Airlines', 'iataCodeShort': '789', 'icaoCode': 'B789', 'model': 'B789', 'modelCode': 'B787-9', 'numSeats': 285, 'rolloutDate': '2018-02-18', 'firstFlightDate': '2018-02-18', 'deliveryDate': '2018-02-28', 'registrationDate': '2018-02-27', 'typeName': 'Boeing 787-9', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 8.3, 'verified': True, 'numRegistrations': 1}
N711ZX {'id': 8609, 'reg': 'N711ZX', 'active': True, 'serial': '28481', 'hexIcao': 'A98219', 'airlineName': 'Delta Air Lines', 'iataCodeShort': '752', 'icaoCode': 'B752', 'model': 'B752', 'modelCode': '757-231', 'numSeats': 168, 'rolloutDate': '1997-05-21', 'firstFlightDate': '1997-05-21', 'deliveryDate': '1997-06-03', 'registrationDate': '2008-01-17', 'typeName': 'Boeing 757-200', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 757', 'ageYears': 29.0, 'verified': True, 'numRegistrations': 3}
N973JT {'id': 27376, 'reg': 'N973JT', 'active': True, 'serial': '8581', 'hexIcao': 'AD8FA4', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '321', 'icaoCode': 'A321', 'model': 'A321', 'modelCode': '321-231', 'numSeats': 200, 'rolloutDate': '2018-11-16', 'firstFlightDate': '2018-11-16', 'deliveryDate': '2018-11-30', 'registrationDate': '2018-11-29', 'typeName': 'Airbus A321', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321', 'ageYears': 7.5, 'verified': True, 'numRegistrations': 1}
N763JB {'id': 15053, 'reg': 'N763JB', 'active': True, 'serial': '3707', 'hexIcao': 'AA4D77', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 162, 'rolloutDate': '2008-11-13', 'firstFlightDate': '2008-11-13', 'deliveryDate': '2008-11-26', 'registrationDate': '2008-11-26', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 17.5, 'verified': True, 'numRegistrations': 1}
B-LXB {'id': 3128, 'reg': 'B-LXB', 'active': True, 'serial': '169', 'hexIcao': '789214', 'airlineName': 'Cathay Pacific', 'iataCodeShort': '350', 'icaoCode': 'A350', 'model': 'A35K', 'modelCode': '350-1041', 'numSeats': 334, 'rolloutDate': '2018-08-01', 'firstFlightDate': '2018-08-01', 'deliveryDate': '2018-08-31', 'registrationDate': '2018-08-31', 'typeName': 'Airbus A350', 'numEngines': 2, 'engineType': 'Turboprop', 'isFreighter': False, 'productionLine': 'Airbus A350', 'ageYears': 7.8, 'verified': True, 'numRegistrations': 1}
B-2092 {'id': 19546, 'reg': 'B-2092', 'active': True, 'serial': '44683', 'hexIcao': '780C5C', 'airlineName': 'Air China', 'iataCodeShort': '777', 'icaoCode': 'B777', 'model': '777', 'modelCode': 'B777-FFT', 'rolloutDate': '2015-01-15', 'firstFlightDate': '2015-01-15', 'deliveryDate': '2015-02-27', 'registrationDate': '2015-02-27', 'typeName': 'Boeing 777', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': True, 'productionLine': 'Boeing 777', 'ageYears': 11.3, 'verified': True, 'numRegistrations': 1}
N828AW {'id': 2795, 'reg': 'N828AW', 'active': True, 'serial': '1552', 'hexIcao': 'AB4EA8', 'airlineName': 'American Airlines', 'iataCodeShort': '319', 'icaoCode': 'A319', 'model': 'A319', 'modelCode': '319-132', 'numSeats': 128, 'rolloutDate': '2001-07-06', 'firstFlightDate': '2001-07-06', 'deliveryDate': '2001-07-31', 'registrationDate': '2015-04-08', 'typeName': 'Airbus A319', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A319', 'ageYears': 24.9, 'verified': True, 'numRegistrations': 3}
G-ZBLB {'id': 50255, 'reg': 'G-ZBLB', 'active': True, 'serial': '60638', 'hexIcao': '4078DE', 'airlineName': 'British Airways', 'iataCodeShort': '781', 'icaoCode': 'B78X', 'model': 'B781', 'modelCode': 'B787-10', 'numSeats': 256, 'rolloutDate': '2020-05-22', 'registrationDate': '2020-06-30', 'typeName': 'Boeing 787-10', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Boeing 787', 'ageYears': 6.0, 'verified': True, 'numRegistrations': 1}
N524JB {'id': 2703, 'reg': 'N524JB', 'active': True, 'serial': '1528', 'hexIcao': 'A69894', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-232', 'numSeats': 150, 'rolloutDate': '2001-06-20', 'firstFlightDate': '2001-06-20', 'deliveryDate': '2001-08-01', 'registrationDate': '2001-08-01', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 24.9, 'verified': True, 'numRegistrations': 1}
N478PX {'id': 2118418, 'reg': 'N478PX', 'active': True, 'serial': '15478', 'hexIcao': 'A5E02D', 'airlineName': 'Endeavor Air', 'iataCodeShort': 'CR9', 'icaoCode': 'CRJ9', 'model': 'CRJ9', 'modelCode': 'CRJ-900LR', 'numSeats': 70, 'rolloutDate': '2019-12-03', 'registrationDate': '2019-12-16', 'typeName': 'Canadair CRJ 900', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Canadair CRJ 900', 'ageYears': 6.5, 'verified': True, 'numRegistrations': 1}
N955JB {'id': 30370, 'reg': 'N955JB', 'active': True, 'serial': '6757', 'hexIcao': 'AD4804', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '321', 'icaoCode': 'A321', 'model': 'A321', 'modelCode': '321-231', 'numSeats': 200, 'rolloutDate': '2015-08-27', 'registrationDate': '2015-09-04', 'typeName': 'Airbus A321', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321', 'ageYears': 10.7, 'verified': True, 'numRegistrations': 1}
N989JT {'id': 26627, 'reg': 'N989JT', 'active': True, 'serial': '7924', 'hexIcao': 'ADCD6D', 'airlineName': 'JetBlue Airways', 'iataCodeShort': '321', 'icaoCode': 'A321', 'model': 'A321', 'modelCode': '321-231', 'numSeats': 159, 'rolloutDate': '2017-12-07', 'firstFlightDate': '2017-12-07', 'deliveryDate': '2017-12-14', 'registrationDate': '2017-12-14', 'typeName': 'Airbus A321', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A321', 'ageYears': 8.5, 'verified': True, 'numRegistrations': 1}

In [ ]:
import pandas as pd

def extract_aircraft_info(aircraft_data):
    extracted_aircraft_info = {
        'aircraft_code': aircraft_data.get('reg'),
        'aircraft_type': aircraft_data.get('typeName'),
        'serial': aircraft_data.get('serial'),
        'model': aircraft_data.get('model'),
        'airline': aircraft_data.get('airlineName'),
        'icao_code': aircraft_data.get('icaoCode'),
        'engine': aircraft_data.get('engineType'),
        'registration': aircraft_data.get('id')         
        }
    return extracted_aircraft_info

In [ ]:
extracted_aircrafts_data = []
for aircraft_code, data in aircraft_all.items():
        extracted_aircrafts_data.append(extract_aircraft_info(data))

# Create a pandas DataFrame from the extracted data
aircraft_df = pd.DataFrame(extracted_aircrafts_data)

aircraft_df_dropped = aircraft_df.dropna() #drops rows with null values since NaN and NaT are not accepteble in sql
display(aircraft_df_dropped)#dropped 2 rows

NameError: name 'aircraft_all' is not defined

In [ ]:
query = """create table if not exists Aircraft(aircraft_id int primary key AUTO_INCREMENT, aircraft_code varchar(60) UNIQUE, aircraft_type varchar(60), serial varchar(60), model varchar(60), airline varchar(60), icao_code varchar(60), engine varchar(60), registration int unique)"""
cursor.execute(query)
connection.commit()

In [ ]:
columns = ",".join(aircraft_df_dropped.columns)
placeholders = ",".join(["%s"]*len(aircraft_df_dropped.columns))
query = f"insert into Aircraft({columns}) values({placeholders})"
tuple_data = []
for i in aircraft_df_dropped.index:
    row = list(aircraft_df_dropped.loc[i].values)
    row[7]=int(row[7])
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()

## 4. Steps to collect airport_delays data using API and convert into SQL

In [9]:
def fetch_airport_delays_data(icao_code):
    url=f"https://aerodatabox.p.rapidapi.com/airports/icao/{icao_code}/delays/2026-05-18T12:00/2026-05-19T00:00"
    airport_delays_response = requests.get(url, headers=headers)
    time.sleep(1)
    return airport_delays_response.json()

In [13]:
airport_delay_list = [
    "EGLL", "KJFK", "OMDB", "VIDP", "VOBL", "EGCC", "EDDM", "CYVR", "RJOO", "WMKP", "VTCC", "EHAM", "LFPG", "WSSS", "YSSY"

]

delay_data_all = {}

for icao in airport_delay_list:
    try:
        airport_delay_data = fetch_airport_delays_data(icao)
        delay_data_all[icao]= airport_delay_data
        print(airport_delay_data)
    except Exception as e:
        print(f"Error loading airport {icao}: {e}")

[{'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 09:00Z', 'local': '2026-05-18 10:00+01:00'}, 'to': {'utc': '2026-05-18 11:00Z', 'local': '2026-05-18 12:00+01:00'}, 'departuresDelayInformation': {'numTotal': 87, 'numQualifiedTotal': 87, 'numCancelled': 0, 'medianDelay': '00:26:00', 'delayIndex': 1.44}, 'arrivalsDelayInformation': {'numTotal': 76, 'numQualifiedTotal': 76, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 09:15Z', 'local': '2026-05-18 10:15+01:00'}, 'to': {'utc': '2026-05-18 11:15Z', 'local': '2026-05-18 12:15+01:00'}, 'departuresDelayInformation': {'numTotal': 85, 'numQualifiedTotal': 85, 'numCancelled': 0, 'medianDelay': '00:26:00', 'delayIndex': 1.44}, 'arrivalsDelayInformation': {'numTotal': 79, 'numQualifiedTotal': 79, 'numCancelled': 1, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 09:30Z', 'local': '2026-05-18 10:30+01:00'}, 'to': {'utc': '2026-05-18 11:30Z', 'local': '2026-05-18 12:30+01:00'}, 'departuresDelayInformation': {'numTotal': 86, 'numQualifiedTotal': 86, 'numCancelled': 0, 'medianDelay': '00:25:00', 'delayIndex': 1.42}, 'arrivalsDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 1, 'medianDelay': '-00:08:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 09:45Z', 'local': '2026-05-18 10:45+01:00'}, 'to': {'utc': '2026-05-18 11:45Z', 'local': '2026-05-18 12:45+01:00'}, 'departuresDelayInformation': {'numTotal': 84, 'numQualifiedTotal': 84, 'numCancelled': 0, 'medianDelay': '00:25:00', 'delayIndex': 1.39}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 1, 'medianDelay': '-00:06:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 10:00Z', 'local': '2026-05-18 11:00+01:00'}, 'to': {'utc': '2026-05-18 12:00Z', 'local': '2026-05-18 13:00+01:00'}, 'departuresDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '00:26:00', 'delayIndex': 1.44}, 'arrivalsDelayInformation': {'numTotal': 76, 'numQualifiedTotal': 76, 'numCancelled': 1, 'medianDelay': '-00:07:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 10:15Z', 'local': '2026-05-18 11:15+01:00'}, 'to': {'utc': '2026-05-18 12:15Z', 'local': '2026-05-18 13:15+01:00'}, 'departuresDelayInformation': {'numTotal': 79, 'numQualifiedTotal': 79, 'numCancelled': 0, 'medianDelay': '00:28:00', 'delayIndex': 1.56}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 1, 'medianDelay': '-00:05:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 10:30Z', 'local': '2026-05-18 11:30+01:00'}, 'to': {'utc': '2026-05-18 12:30Z', 'local': '2026-05-18 13:30+01:00'}, 'departuresDelayInformation': {'numTotal': 85, 'numQualifiedTotal': 85, 'numCancelled': 0, 'medianDelay': '00:30:00', 'delayIndex': 1.67}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 1, 'medianDelay': '-00:05:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 10:45Z', 'local': '2026-05-18 11:45+01:00'}, 'to': {'utc': '2026-05-18 12:45Z', 'local': '2026-05-18 13:45+01:00'}, 'departuresDelayInformation': {'numTotal': 86, 'numQualifiedTotal': 86, 'numCancelled': 0, 'medianDelay': '00:30:00', 'delayIndex': 1.67}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 1, 'medianDelay': '-00:05:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 11:00Z', 'local': '2026-05-18 12:00+01:00'}, 'to': {'utc': '2026-05-18 13:00Z', 'local': '2026-05-18 14:00+01:00'}, 'departuresDelayInformation': {'numTotal': 84, 'numQualifiedTotal': 84, 'numCancelled': 0, 'medianDelay': '00:30:00', 'delayIndex': 1.67}, 'arrivalsDelayInformation': {'numTotal': 82, 'numQualifiedTotal': 82, 'numCancelled': 1, 'medianDelay': '-00:06:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 11:15Z', 'local': '2026-05-18 12:15+01:00'}, 'to': {'utc': '2026-05-18 13:15Z', 'local': '2026-05-18 14:15+01:00'}, 'departuresDelayInformation': {'numTotal': 86, 'numQualifiedTotal': 86, 'numCancelled': 0, 'medianDelay': '00:31:00', 'delayIndex': 1.72}, 'arrivalsDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 0, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 11:30Z', 'local': '2026-05-18 12:30+01:00'}, 'to': {'utc': '2026-05-18 13:30Z', 'local': '2026-05-18 14:30+01:00'}, 'departuresDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 0, 'medianDelay': '00:31:00', 'delayIndex': 1.72}, 'arrivalsDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 0, 'medianDelay': '-00:08:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 11:45Z', 'local': '2026-05-18 12:45+01:00'}, 'to': {'utc': '2026-05-18 13:45Z', 'local': '2026-05-18 14:45+01:00'}, 'departuresDelayInformation': {'numTotal': 80, 'numQualifiedTotal': 80, 'numCancelled': 0, 'medianDelay': '00:32:00', 'delayIndex': 1.78}, 'arrivalsDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 0, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 12:00Z', 'local': '2026-05-18 13:00+01:00'}, 'to': {'utc': '2026-05-18 14:00Z', 'local': '2026-05-18 15:00+01:00'}, 'departuresDelayInformation': {'numTotal': 86, 'numQualifiedTotal': 86, 'numCancelled': 0, 'medianDelay': '00:32:00', 'delayIndex': 1.81}, 'arrivalsDelayInformation': {'numTotal': 84, 'numQualifiedTotal': 84, 'numCancelled': 0, 'medianDelay': '-00:08:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 12:15Z', 'local': '2026-05-18 13:15+01:00'}, 'to': {'utc': '2026-05-18 14:15Z', 'local': '2026-05-18 15:15+01:00'}, 'departuresDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 0, 'medianDelay': '00:32:00', 'delayIndex': 1.78}, 'arrivalsDelayInformation': {'numTotal': 82, 'numQualifiedTotal': 82, 'numCancelled': 1, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 12:30Z', 'local': '2026-05-18 13:30+01:00'}, 'to': {'utc': '2026-05-18 14:30Z', 'local': '2026-05-18 15:30+01:00'}, 'departuresDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '00:34:00', 'delayIndex': 1.89}, 'arrivalsDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 1, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 12:45Z', 'local': '2026-05-18 13:45+01:00'}, 'to': {'utc': '2026-05-18 14:45Z', 'local': '2026-05-18 15:45+01:00'}, 'departuresDelayInformation': {'numTotal': 76, 'numQualifiedTotal': 76, 'numCancelled': 0, 'medianDelay': '00:35:00', 'delayIndex': 1.97}, 'arrivalsDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 1, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 13:00Z', 'local': '2026-05-18 14:00+01:00'}, 'to': {'utc': '2026-05-18 15:00Z', 'local': '2026-05-18 16:00+01:00'}, 'departuresDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 0, 'medianDelay': '00:36:00', 'delayIndex': 2.03}, 'arrivalsDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 1, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 13:15Z', 'local': '2026-05-18 14:15+01:00'}, 'to': {'utc': '2026-05-18 15:15Z', 'local': '2026-05-18 16:15+01:00'}, 'departuresDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 0, 'medianDelay': '00:36:00', 'delayIndex': 2.03}, 'arrivalsDelayInformation': {'numTotal': 79, 'numQualifiedTotal': 79, 'numCancelled': 1, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 13:30Z', 'local': '2026-05-18 14:30+01:00'}, 'to': {'utc': '2026-05-18 15:30Z', 'local': '2026-05-18 16:30+01:00'}, 'departuresDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 0, 'medianDelay': '00:39:00', 'delayIndex': 2.17}, 'arrivalsDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 1, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 13:45Z', 'local': '2026-05-18 14:45+01:00'}, 'to': {'utc': '2026-05-18 15:45Z', 'local': '2026-05-18 16:45+01:00'}, 'departuresDelayInformation': {'numTotal': 83, 'numQualifiedTotal': 83, 'numCancelled': 0, 'medianDelay': '00:40:00', 'delayIndex': 2.22}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 1, 'medianDelay': '-00:11:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 14:00Z', 'local': '2026-05-18 15:00+01:00'}, 'to': {'utc': '2026-05-18 16:00Z', 'local': '2026-05-18 17:00+01:00'}, 'departuresDelayInformation': {'numTotal': 84, 'numQualifiedTotal': 84, 'numCancelled': 1, 'medianDelay': '00:40:00', 'delayIndex': 2.25}, 'arrivalsDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 1, 'medianDelay': '-00:11:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 14:15Z', 'local': '2026-05-18 15:15+01:00'}, 'to': {'utc': '2026-05-18 16:15Z', 'local': '2026-05-18 17:15+01:00'}, 'departuresDelayInformation': {'numTotal': 85, 'numQualifiedTotal': 85, 'numCancelled': 1, 'medianDelay': '00:41:00', 'delayIndex': 2.28}, 'arrivalsDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 0, 'medianDelay': '-00:11:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 14:30Z', 'local': '2026-05-18 15:30+01:00'}, 'to': {'utc': '2026-05-18 16:30Z', 'local': '2026-05-18 17:30+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 1, 'medianDelay': '00:41:00', 'delayIndex': 2.31}, 'arrivalsDelayInformation': {'numTotal': 81, 'numQualifiedTotal': 81, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 14:45Z', 'local': '2026-05-18 15:45+01:00'}, 'to': {'utc': '2026-05-18 16:45Z', 'local': '2026-05-18 17:45+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 1, 'medianDelay': '00:42:00', 'delayIndex': 2.33}, 'arrivalsDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 0, 'medianDelay': '-00:13:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 15:00Z', 'local': '2026-05-18 16:00+01:00'}, 'to': {'utc': '2026-05-18 17:00Z', 'local': '2026-05-18 18:00+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 1, 'medianDelay': '00:42:00', 'delayIndex': 2.36}, 'arrivalsDelayInformation': {'numTotal': 76, 'numQualifiedTotal': 76, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 15:15Z', 'local': '2026-05-18 16:15+01:00'}, 'to': {'utc': '2026-05-18 17:15Z', 'local': '2026-05-18 18:15+01:00'}, 'departuresDelayInformation': {'numTotal': 91, 'numQualifiedTotal': 91, 'numCancelled': 1, 'medianDelay': '00:40:00', 'delayIndex': 2.28}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 15:30Z', 'local': '2026-05-18 16:30+01:00'}, 'to': {'utc': '2026-05-18 17:30Z', 'local': '2026-05-18 18:30+01:00'}, 'departuresDelayInformation': {'numTotal': 89, 'numQualifiedTotal': 89, 'numCancelled': 1, 'medianDelay': '00:41:00', 'delayIndex': 2.28}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 0, 'medianDelay': '-00:13:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 15:45Z', 'local': '2026-05-18 16:45+01:00'}, 'to': {'utc': '2026-05-18 17:45Z', 'local': '2026-05-18 18:45+01:00'}, 'departuresDelayInformation': {'numTotal': 91, 'numQualifiedTotal': 91, 'numCancelled': 1, 'medianDelay': '00:40:00', 'delayIndex': 2.22}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '-00:13:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 16:00Z', 'local': '2026-05-18 17:00+01:00'}, 'to': {'utc': '2026-05-18 18:00Z', 'local': '2026-05-18 19:00+01:00'}, 'departuresDelayInformation': {'numTotal': 91, 'numQualifiedTotal': 91, 'numCancelled': 0, 'medianDelay': '00:38:00', 'delayIndex': 2.11}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 16:15Z', 'local': '2026-05-18 17:15+01:00'}, 'to': {'utc': '2026-05-18 18:15Z', 'local': '2026-05-18 19:15+01:00'}, 'departuresDelayInformation': {'numTotal': 91, 'numQualifiedTotal': 91, 'numCancelled': 0, 'medianDelay': '00:37:00', 'delayIndex': 2.06}, 'arrivalsDelayInformation': {'numTotal': 74, 'numQualifiedTotal': 74, 'numCancelled': 0, 'medianDelay': '-00:13:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 16:30Z', 'local': '2026-05-18 17:30+01:00'}, 'to': {'utc': '2026-05-18 18:30Z', 'local': '2026-05-18 19:30+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 0, 'medianDelay': '00:37:00', 'delayIndex': 2.06}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 0, 'medianDelay': '-00:12:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 16:45Z', 'local': '2026-05-18 17:45+01:00'}, 'to': {'utc': '2026-05-18 18:45Z', 'local': '2026-05-18 19:45+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 0, 'medianDelay': '00:36:00', 'delayIndex': 2.0}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 0, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 17:00Z', 'local': '2026-05-18 18:00+01:00'}, 'to': {'utc': '2026-05-18 19:00Z', 'local': '2026-05-18 20:00+01:00'}, 'departuresDelayInformation': {'numTotal': 92, 'numQualifiedTotal': 92, 'numCancelled': 0, 'medianDelay': '00:35:00', 'delayIndex': 1.94}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 17:15Z', 'local': '2026-05-18 18:15+01:00'}, 'to': {'utc': '2026-05-18 19:15Z', 'local': '2026-05-18 20:15+01:00'}, 'departuresDelayInformation': {'numTotal': 93, 'numQualifiedTotal': 93, 'numCancelled': 0, 'medianDelay': '00:34:00', 'delayIndex': 1.89}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 17:30Z', 'local': '2026-05-18 18:30+01:00'}, 'to': {'utc': '2026-05-18 19:30Z', 'local': '2026-05-18 20:30+01:00'}, 'departuresDelayInformation': {'numTotal': 97, 'numQualifiedTotal': 97, 'numCancelled': 0, 'medianDelay': '00:31:00', 'delayIndex': 1.72}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 0, 'medianDelay': '-00:08:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 17:45Z', 'local': '2026-05-18 18:45+01:00'}, 'to': {'utc': '2026-05-18 19:45Z', 'local': '2026-05-18 20:45+01:00'}, 'departuresDelayInformation': {'numTotal': 95, 'numQualifiedTotal': 95, 'numCancelled': 0, 'medianDelay': '00:31:00', 'delayIndex': 1.72}, 'arrivalsDelayInformation': {'numTotal': 74, 'numQualifiedTotal': 74, 'numCancelled': 0, 'medianDelay': '-00:08:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 18:00Z', 'local': '2026-05-18 19:00+01:00'}, 'to': {'utc': '2026-05-18 20:00Z', 'local': '2026-05-18 21:00+01:00'}, 'departuresDelayInformation': {'numTotal': 92, 'numQualifiedTotal': 92, 'numCancelled': 0, 'medianDelay': '00:27:00', 'delayIndex': 1.53}, 'arrivalsDelayInformation': {'numTotal': 74, 'numQualifiedTotal': 74, 'numCancelled': 0, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 18:15Z', 'local': '2026-05-18 19:15+01:00'}, 'to': {'utc': '2026-05-18 20:15Z', 'local': '2026-05-18 21:15+01:00'}, 'departuresDelayInformation': {'numTotal': 91, 'numQualifiedTotal': 91, 'numCancelled': 0, 'medianDelay': '00:26:00', 'delayIndex': 1.44}, 'arrivalsDelayInformation': {'numTotal': 73, 'numQualifiedTotal': 73, 'numCancelled': 0, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 18:30Z', 'local': '2026-05-18 19:30+01:00'}, 'to': {'utc': '2026-05-18 20:30Z', 'local': '2026-05-18 21:30+01:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 90, 'numCancelled': 0, 'medianDelay': '00:23:00', 'delayIndex': 1.31}, 'arrivalsDelayInformation': {'numTotal': 73, 'numQualifiedTotal': 73, 'numCancelled': 0, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 18:45Z', 'local': '2026-05-18 19:45+01:00'}, 'to': {'utc': '2026-05-18 20:45Z', 'local': '2026-05-18 21:45+01:00'}, 'departuresDelayInformation': {'numTotal': 84, 'numQualifiedTotal': 84, 'numCancelled': 0, 'medianDelay': '00:22:00', 'delayIndex': 1.22}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 0, 'medianDelay': '-00:11:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 19:00Z', 'local': '2026-05-18 20:00+01:00'}, 'to': {'utc': '2026-05-18 21:00Z', 'local': '2026-05-18 22:00+01:00'}, 'departuresDelayInformation': {'numTotal': 78, 'numQualifiedTotal': 78, 'numCancelled': 0, 'medianDelay': '00:20:00', 'delayIndex': 1.11}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 1, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 19:15Z', 'local': '2026-05-18 20:15+01:00'}, 'to': {'utc': '2026-05-18 21:15Z', 'local': '2026-05-18 22:15+01:00'}, 'departuresDelayInformation': {'numTotal': 69, 'numQualifiedTotal': 69, 'numCancelled': 0, 'medianDelay': '00:19:00', 'delayIndex': 1.06}, 'arrivalsDelayInformation': {'numTotal': 75, 'numQualifiedTotal': 75, 'numCancelled': 1, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 19:30Z', 'local': '2026-05-18 20:30+01:00'}, 'to': {'utc': '2026-05-18 21:30Z', 'local': '2026-05-18 22:30+01:00'}, 'departuresDelayInformation': {'numTotal': 62, 'numQualifiedTotal': 62, 'numCancelled': 1, 'medianDelay': '00:19:00', 'delayIndex': 1.08}, 'arrivalsDelayInformation': {'numTotal': 77, 'numQualifiedTotal': 77, 'numCancelled': 1, 'medianDelay': '-00:10:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 19:45Z', 'local': '2026-05-18 20:45+01:00'}, 'to': {'utc': '2026-05-18 21:45Z', 'local': '2026-05-18 22:45+01:00'}, 'departuresDelayInformation': {'numTotal': 60, 'numQualifiedTotal': 60, 'numCancelled': 1, 'medianDelay': '00:20:00', 'delayIndex': 1.11}, 'arrivalsDelayInformation': {'numTotal': 73, 'numQualifiedTotal': 73, 'numCancelled': 1, 'medianDelay': '-00:09:00', 'delayIndex': 0.0}}, {'airportIcao': 'EGLL', 'from': {'utc': '2026-05-18 20:00Z', 'local': '2026-05-18 21:00+01:00'}, 'to': {'utc': '2026-05-18 22:00Z', 'local': '2026-05-18 23:00+01:00'}, 'departuresDelayInformation': {'numTotal': 57, 'numQualifiedTotal': 57, 'numCancelled': 1, 'medianDelay': '00:24:00', 'delayIndex': 1.39}, 'arrivalsDelayInformation': {'numTotal': 64, 'numQualifiedTotal': 64, 'numCancelled': 1, 'medianDelay': '-00:09:0

In [21]:
import pandas as pd
def extract_delay_info(delay_data):
    extracted_delay_info_list=[]
    for dic in delay_data:
        extracted_delay_info = {
            'icao_code': dic.get('airportIcao'),
            'date': dic.get('from', {}).get('utc', '').split(" ")[0],
            'from_time': dic.get('from', {}).get('utc', '').split(" ")[1],
            'to_time': dic.get('to', {}).get('utc', '').split(" ")[1],
            'dep_median_delay': dic.get('departuresDelayInformation', {}).get('medianDelay', ''),
            'dep_cancelled_flight': dic.get('departuresDelayInformation', {}).get('numCancelled', ''),
            'arr_median_delay': dic.get('arrivalsDelayInformation', {}).get('medianDelay', ''),
            'arr_cancelled_flight': dic.get('arrivalsDelayInformation', {}).get('numCancelled', ''),
            'total_flights': dic.get('departuresDelayInformation', {}).get('numTotal', 0)
        
        }
        extracted_delay_info_list.append(extracted_delay_info)
    return extracted_delay_info_list
    
extracted_delay_data=[]
for icao, data in delay_data_all.items():
    extracted_delay_data.extend(extract_delay_info(data))
    #not using append because Since extract_delay_info(data) already returns a list, append() adds the whole list as one item

# Create DataFrame
delay_df = pd.DataFrame(extracted_delay_data)

display(delay_df)

,icao_code,date,from_time,to_time,dep_median_delay,dep_cancelled_flight,arr_median_delay,arr_cancelled_flight,total_flights
0,EGLL,2026-05-18,09:00Z,11:00Z,00:26:00,0,-00:12:00,0,87
1,EGLL,2026-05-18,09:15Z,11:15Z,00:26:00,0,-00:09:00,1,85
2,EGLL,2026-05-18,09:30Z,11:30Z,00:25:00,0,-00:08:00,1,86
3,EGLL,2026-05-18,09:45Z,11:45Z,00:25:00,0,-00:06:00,1,84
4,EGLL,2026-05-18,10:00Z,12:00Z,00:26:00,0,-00:07:00,1,77
...,...,...,...,...,...,...,...,...,...
730,YSSY,2026-05-18,11:00Z,13:00Z,00:00:00,1,00:01:00,0,11
731,YSSY,2026-05-18,11:15Z,13:15Z,,0,00:00:00,0,9
732,YSSY,2026-05-18,11:30Z,13:30Z,,0,-00:06:00,0,7
733,YSSY,2026-05-18,11:45Z,13:45Z,,0,00:03:00,0,7
734,YSSY,2026-05-18,12:00Z,14:00Z,,0,00:01:00,0,4

In [29]:
delay_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   icao_code             735 non-null    str
 1   date                  735 non-null    str
 2   from                  735 non-null    str
 3   to                    735 non-null    str
 4   dep_median_delay      735 non-null    str
 5   dep_cancelled_flight  735 non-null    int64
 6   arr_median_delay      735 non-null    str
 7   arr_cancelled_flight  735 non-null    int64
 8   total_flights         735 non-null    int64
dtypes: int64(3), str(6)
memory usage: 51.8 KB

In [6]:
query="""create table if not exists airport_delay(delay_id int primary key auto_increment, icao_code varchar(60), date varchar(60), from_time varchar(60), to_time varchar(60), dep_median_delay varchar(60), dep_cancelled_flight int, arr_median_delay varchar(60), arr_cancelled_flight int, total_flights int)"""
cursor.execute(query)

In [22]:
columns = ','.join(delay_df.columns)
placeholders = ','.join(['%s']*len(delay_df.columns))
query = f"insert into airport_delay({columns}) values({placeholders})"
tuple_data = []
for i in delay_df.index:
    row = list(delay_df.loc[i].values)
    row[5]=int(row[5])
    row[7]=int(row[7])
    row[8]=int(row[8])
    row = tuple(row)
    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()

# SQL Queries

## 1. Show the total number of flights for each aircraft model, listing the model and its count.

In [ ]:
query = "SELECT ROW_NUMBER() OVER () AS no, model, COUNT(flight_number) AS Total_flights FROM aircraft JOIN flight ON aircraft_code=aircraft_registration  GROUP BY model"

df=pd.read_sql(query, connection)
print(df.to_string(index=False))
#verified manually using SELECT model, aircraft_code, aircraft_registration, COUNT( aircraft_registration) as total_flight FROM flight JOIN aircraft on aircraft_code=aircraft_registration where model = 'A20N' group by model, aircraft_code, aircraft_registration;

 no model  Total_flights
  1  B744              1
  2  A20N             17
  3  A320             16
  4  A21N             14
  5  AT75              2
  6  A321              6
  7  E170              1
  8  B738              8
  9  B789              7
 10  E175              1
 11  A319              5
 12  A388              7
 13  B773             12
 14  B772              1
 15  B781              1
 16   777              2
 17  A35K              1
 18  A333              2
 19  CRJ9              3
 20  B752              1
 21  A359              1
 22  B38M              5
 23  B788              2
 24  A332              1

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\3108856341.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

## 2. List all aircraft (registration, model) that have been assigned to more than 5 flights

In [32]:
#since flight count is not more than 4, i used greater than or equal to 3
query = """SELECT aircraft_registration, model, COUNT(*) AS flight_count 
FROM aircraft JOIN flight 
ON aircraft_code = aircraft_registration 
GROUP BY aircraft_code, model 
HAVING COUNT(*) >=3"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\3830913986.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  aircraft_registration model  flight_count
0                G-EUYV  A320             4
1                G-XLED  A388             4
2                EI-SIA  A20N             3
3                4X-EDA  B789             3
4                G-EUYC  A320             3
5                D-AGWV  A319             4

## 3. For each airport, display its name and the number of outbound flights, but only for airports with more than 5 flights.

In [39]:
query = "SELECT icao_code, name, COUNT(flight_number) as number_of_outbound_flights from airport join flight on icao_code=origin_icao GROUP BY icao_code having count(flight_number)>5"
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\4238549280.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   icao_code                     name  number_of_outbound_flights
0       YSSY   Sydney Kingsford Smith                          20
1       VOBL      Bangalore Bengaluru                          21
2       OMDB                    Dubai                          22
3       VIDP  New Delhi Indira Gandhi                          21
4       EHAM       Amsterdam Schiphol                          22
5       VTCC     Chiangmai Chiang Mai                          20
6       EDDM                   Munich                          21
7       KJFK  New York John F Kennedy                          21
8       EGLL          London Heathrow                          22
9       CYVR                Vancouver                          20
10      WSSS         Singapore Changi                          26
11      WMKP                   Penang                          20
12      LFPG  Paris Charles de Gaulle                          21
13      EGCC               Manchester                          22
14      RJOO                    Osaka                          20

## 4. Find the top 3 destination airports (name, city) by number of arriving flights, sorted by count descending.

In [44]:
query = """SELECT destination_icao, name, city, COUNT(flight_number) AS arriving_flights
 FROM flight JOIN airport ON destination_icao = icao_code
   GROUP BY icao_code 
   ORDER BY arriving_flights DESC
     LIMIT 3"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\2126184087.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  destination_icao                     name       city  arriving_flights
0             WSSS         Singapore Changi  Singapore                28
1             LFPG  Paris Charles de Gaulle      Paris                26
2             EGLL          London Heathrow     London                24

## 5. Show for each flight: number, origin, destination, and a label 'Domestic' or 'International' using CASE WHEN on country match

In [46]:
query = """SELECT flight_number, origin_icao, destination_icao,
CASE 
WHEN airport1.country = airport2.country 
THEN 'Domestic' ELSE 'International'
END AS flight_type
 FROM flight 
 JOIN airport AS airport1 on origin_icao=airport1.icao_code 
  JOIN airport AS airport2 on destination_icao = airport2.icao_code """
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\1675702155.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   flight_number origin_icao destination_icao    flight_type
0        6E 1657        VIDP             OMDB  International
1        6E 3223        EHAM             LFPG  International
2         6E 817        VOBL             VIDP       Domestic
3         6E 861        VIDP             VOBL       Domestic
4         AA 141        EGLL             KJFK  International
5         AA 292        KJFK             VIDP  International
6        AC 5944        WSSS             WMKP  International
7        AC 5948        WMKP             WSSS  International
8        AC 7610        OMDB             WSSS  International
9         AC 860        CYVR             EGLL  International
10       AF 8345        EHAM             LFPG  International
11       AI 2807        VIDP             VOBL       Domestic
12       AI 2813        VIDP             VOBL       Domestic
13       AI 2818        VOBL             VIDP       Domestic
14        AI 301        YSSY             VIDP  International
15       AK 1730        WSSS             WMKP  International
16       BA 1373        EGCC             EGLL       Domestic
17        BA 176        KJFK             EGLL  International
18        BA 179        EGLL             KJFK  International
19         BA 84        CYVR             EGLL  International
20       CI 9599        EHAM             LFPG  International
21       DE 5969        OMDB             WSSS  International
22         EK 22        EGCC             OMDB  International
23        EK 314        OMDB             WSSS  International
24         EK 51        OMDB             EDDM  International
25        EK 514        OMDB             VIDP  International
26        EK 568        OMDB             VOBL  International
27         EK 72        LFPG             OMDB  International
28       GA 9258        EHAM             LFPG  International
29       IX 1040        VOBL             VIDP       Domestic
30       KL 1037        EHAM             EGCC  International
31       KL 1038        EGCC             EHAM  International
32       KL 1411        EHAM             LFPG  International
33       KL 1857        EHAM             EDDM  International
34       KL 1858        EDDM             EHAM  International
35        KL 646        KJFK             EHAM  International
36       LH 2310        EDDM             EHAM  International
37       MK 7595        EHAM             LFPG  International
38        OD 832        WSSS             WMKP  International
39       QF 8022        EGCC             OMDB  International
40       QF 8382        OMDB             WSSS  International
41        SQ 141        WMKP             WSSS  International
42        SQ 142        WSSS             WMKP  International
43       SQ 8352        WSSS             WMKP  International
44       SQ 8353        WMKP             WSSS  International
45        TR 498        WSSS             WMKP  International
46        TR 499        WMKP             WSSS  International
47       VL 2308        EDDM             EHAM  International
48        VS 128        KJFK             EGCC  International

## 6. Show the 5 most recent arrivals at “DEL” airport including flight number, aircraft, departure airport name, and arrival time, ordered by latest arrival.

In [ ]:
query = """SELECT city, flight_number, aircraft_code AS aircraft, name AS departure_airport_name, 
actual_arrival, DATE_FORMAT(STR_TO_DATE(actual_arrival, '%Y-%m-%d %H:%iZ'), '%H:%i') AS arrival_time 
FROM airport 
JOIN flight ON airport.icao_code = flight.origin_icao
JOIN aircraft ON aircraft.aircraft_code=flight.aircraft_registration 
WHERE iata_code = 'DEL'
ORDER BY arrival_time DESC
LIMIT 5"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\1803676126.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

,city,flight_number,aircraft,departure_airport_name,actual_arrival,arrival_time
0,New Delhi,AI 358,VT-TSN,New Delhi Indira Gandhi,2026-05-17 22:08Z,22:08
1,New Delhi,MU 564,B-8226,New Delhi Indira Gandhi,2026-05-17 20:11Z,20:11
2,New Delhi,6E 1701,VT-IPG,New Delhi Indira Gandhi,2026-05-17 20:00Z,20:00
3,New Delhi,6E 1657,VT-IPY,New Delhi Indira Gandhi,2026-05-17 18:12Z,18:12
4,New Delhi,6E 772,VT-IWN,New Delhi Indira Gandhi,2026-05-17 18:00Z,18:00

## 7. Find all airports with no arriving flights (never used as a destination in flights table)

In [63]:
query = """SELECT icao_code, name, city
FROM airport
LEFT JOIN flight ON airport.icao_code = flight.destination_icao
WHERE flight.destination_icao= 'None'"""
df= pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\2695690141.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df= pd.read_sql(query, connection)

Empty DataFrame
Columns: [icao_code, name, city]
Index: []

## 8. For each airline, count the number of flights by status (e.g., 'On Time', 'Delayed', 'Cancelled') using CASE WHEN.

In [82]:
query = """WITH base AS (SELECT aircraft.airline,
        STR_TO_DATE(flight.scheduled_departure, '%Y-%m-%d %H:%iZ') AS sch_dep,
        STR_TO_DATE(flight.actual_departure, '%Y-%m-%d %H:%iZ') AS act_dep,
        STR_TO_DATE(flight.scheduled_arrival, '%Y-%m-%d %H:%iZ') AS sch_arr,
        STR_TO_DATE(flight.actual_arrival, '%Y-%m-%d %H:%iZ') AS act_arr 
        FROM flight
        JOIN aircraft ON aircraft.aircraft_code = flight.aircraft_registration)        
    SELECT airline,
    SUM(CASE 
        WHEN TIMESTAMPDIFF(MINUTE, sch_dep, act_dep) > 0 
        THEN 1 ELSE 0
    END) AS delayed_departure,
    SUM(CASE 
        WHEN TIMESTAMPDIFF(MINUTE, sch_dep, act_dep) <= 0 
        THEN 1 ELSE 0
    END) AS on_time_departure,
    SUM(CASE 
        WHEN TIMESTAMPDIFF(MINUTE, sch_arr, act_arr) > 0 
        THEN 1 ELSE 0
    END) AS delayed_arrival,
    SUM(CASE 
        WHEN TIMESTAMPDIFF(MINUTE, sch_arr, act_arr) <= 0 
        THEN 1 ELSE 0
    END) AS on_time_arrival
FROM base
Group BY airline"""

df= pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_13256\2336441354.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df= pd.read_sql(query, connection)

,airline,delayed_departure,on_time_departure,delayed_arrival,on_time_arrival
0,UPS,0.0,1.0,0.0,0.0
1,IndiGo,2.0,15.0,3.0,13.0
2,Alliance Air,0.0,1.0,0.0,1.0
3,American Airlines,5.0,0.0,0.0,6.0
4,Republic Airways,2.0,0.0,0.0,2.0
5,British Airways,15.0,1.0,9.0,7.0
6,Air India,2.0,3.0,1.0,4.0
7,Vistara,0.0,1.0,0.0,1.0
8,SAS Ireland,3.0,0.0,0.0,3.0
9,El Al,0.0,3.0,0.0,3.0
10,JetBlue Airways,3.0,7.0,1.0,9.0
11,Air China,0.0,0.0,0.0,2.0
12,Cathay Pacific,0.0,2.0,0.0,2.0
13,Delta Air Lines,6.0,0.0,2.0,4.0
14,Endeavor Air,3.0,0.0,0.0,3.0
15,Emirates,6.0,2.0,1.0,7.0
16,flydubai,2.0,3.0,0.0,4.0
17,Eurowings,4.0,0.0,4.0,0.0
18,Air India Express,1.0,6.0,2.0,5.0
19,Korean Air,2.0,0.0,0.0,2.0
20,KLM,1.0,0.0,0.0,1.0
21,LATAM Chile,1.0,0.0,0.0,1.0
22,China Eastern Airlines,1.0,1.0,1.0,1.0
23,Qantas,1.0,0.0,0.0,1.0
24,Air G,0.0,1.0,0.0,1.0
25,Royal Jordanian,0.0,1.0,0.0,1.0
26,SpiceJet,0.0,2.0,0.0,2.0
27,Saudi Arabian Airlines,0.0,1.0,0.0,0.0
28,Turkish Airlines,1.0,0.0,0.0,1.0
29,Virgin Atlantic,1.0,0.0,0.0,1.0

## 9. Show all cancelled flights, with aircraft and both airports, ordered by departure time descending

## 10. List all city pairs (origin-destination) that have more than 2 different aircraft models operating flights between them

In [7]:
query = """SELECT airport_departure.city AS origin_city,
    airport_arrival.city AS destination_city,
    COUNT(DISTINCT aircraft.model) AS aircraft_model_count
FROM flight JOIN airport airport_departure
    ON flight.origin_icao = airport_departure.icao_code
JOIN airport airport_arrival ON flight.destination_icao = airport_arrival.icao_code
JOIN aircraft ON flight.aircraft_registration = aircraft.aircraft_code
GROUP BY airport_departure.city, airport_arrival.city 
HAVING COUNT(DISTINCT aircraft.model) >= 2"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_20248\2828516602.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  origin_city destination_city  aircraft_model_count
0   Bangalore        New Delhi                     2
1      London         New York                     2
2   New Delhi        Bangalore                     2

## 11. For each destination airport, compute the % of delayed flights (status='Delayed') among all arrivals, sorted by highest percentage

In [8]:
query = """WITH base AS (SELECT
        flight.destination_icao,
        STR_TO_DATE(flight.scheduled_arrival, '%Y-%m-%d %H:%iZ') AS sch_arr,
        STR_TO_DATE(flight.actual_arrival, '%Y-%m-%d %H:%iZ') AS act_arr
    FROM flight)
SELECT destination_icao,
    COUNT(*) AS total_flights,
    SUM(CASE 
        WHEN TIMESTAMPDIFF(MINUTE, sch_arr, act_arr) > 0 
        THEN 1 ELSE 0 
        END) AS delayed_flights,
    ROUND(100.0 * SUM(CASE 
            WHEN TIMESTAMPDIFF(MINUTE, sch_arr, act_arr) > 0 
            THEN 1 ELSE 0 
            END) / COUNT(*), 2) AS delayed_percentage
FROM base GROUP BY destination_icao ORDER BY delayed_percentage DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_20248\1103599209.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

    destination_icao  total_flights  delayed_flights  delayed_percentage
0               KLAS              1              1.0               100.0
1               CYQQ              1              1.0               100.0
2               KSFO              2              2.0               100.0
3               LROP              5              5.0               100.0
4               LOWW              2              2.0               100.0
..               ...            ...              ...                 ...
134             LTFM              1              0.0                 0.0
135             YPPH              1              0.0                 0.0
136             LRTR              1              0.0                 0.0
137             LEBL              1              0.0                 0.0
138             YMAY              1              0.0                 0.0

[139 rows x 4 columns]